// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { accountsGenerateInvitationData, accountsGenerateInvitationResponses, accountsInvitationsData, accountsInvitationsErrors, accountsInvitationsResponses, accountsLoginData, accountsLoginErrors, accountsLoginResponses, accountsMeData, accountsMeResponses, accountsRegisterData, accountsRegisterErrors, accountsRegisterResponses, accountsRevokeData, accountsRevokeErrors, accountsRevokeResponses, accountsTrainingAccessData, accountsTrainingAccessResponses, healthHealthData, healthHealthResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AccountsService {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = true>(options: Options<accountsLoginData, ThrowOnError>) {
        return (options.client ?? client).post<accountsLoginResponses, accountsLoginErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }
    
    /**
     * Me
     */
    public static me<ThrowOnError extends boolean = true>(options?: Options<accountsMeData, ThrowOnError>) {
        return (options?.client ?? client).get<accountsMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Training Access
     */
    public static trainingAccess<ThrowOnError extends boolean = true>(options?: Options<accountsTrainingAccessData, ThrowOnError>) {
        return (options?.client ?? client).get<accountsTrainingAccessResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/training/access',
            ...options
        });
    }
    
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = true>(options: Options<accountsRegisterData, ThrowOnError>) {
        return (options.client ?? client).post<accountsRegisterResponses, accountsRegisterErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/users/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Invitations
     */
    public static invitations<ThrowOnError extends boolean = true>(options?: Options<accountsInvitationsData, ThrowOnError>) {
        return (options?.client ?? client).get<accountsInvitationsResponses, accountsInvitationsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/invitations',
            ...options
        });
    }
    
    /**
     * Generate Invitation
     */
    public static generateInvitation<ThrowOnError extends boolean = true>(options?: Options<accountsGenerateInvitationData, ThrowOnError>) {
        return (options?.client ?? client).post<accountsGenerateInvitationResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/invitations',
            ...options
        });
    }
    
    /**
     * Revoke
     */
    public static revoke<ThrowOnError extends boolean = true>(options: Options<accountsRevokeData, ThrowOnError>) {
        return (options.client ?? client).post<accountsRevokeResponses, accountsRevokeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/invitations/{invitation_id}/revoke',
            ...options
        });
    }
}

export class HealthService {
    /**
     * Health
     */
    public static health<ThrowOnError extends boolean = true>(options?: Options<healthHealthData, ThrowOnError>) {
        return (options?.client ?? client).get<healthHealthResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/health',
            ...options
        });
    }
}
