// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Background
 */
export type Background = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Boundary
     */
    boundary: string;
};

/**
 * Body_accounts-login
 */
export type Body_accounts_login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Capability
 */
export type Capability = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Background Id
     */
    background_id: string;
    /**
     * Levels
     */
    levels: Array<Level>;
};

/**
 * Catalog
 */
export type Catalog = {
    /**
     * Version
     */
    version: string;
    /**
     * Quality
     */
    quality: string;
    /**
     * Difficulty Criteria
     */
    difficulty_criteria: {
        [key: string]: string;
    };
    /**
     * Backgrounds
     */
    backgrounds: Array<Background>;
    /**
     * Domains
     */
    domains: [
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain
    ];
};

/**
 * Domain
 */
export type Domain = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Capabilities
     */
    capabilities: Array<Capability>;
    /**
     * Examples
     */
    examples: Array<Example>;
};

/**
 * EvidenceKey
 */
export type EvidenceKey = {
    /**
     * Capability Id
     */
    capability_id: string;
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Background Id
     */
    background_id: string;
};

/**
 * Example
 */
export type Example = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Capability Ids
     */
    capability_ids: Array<string>;
    /**
     * Task
     */
    task: string;
    /**
     * Acceptable
     */
    acceptable: string;
    /**
     * Insufficient
     */
    insufficient: string;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InvitationPublic
 */
export type InvitationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Status
     */
    status: 'unused' | 'used' | 'revoked';
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Level
 */
export type Level = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Required
     */
    required?: Array<EvidenceKey>;
    /**
     * Alternatives
     */
    alternatives?: Array<Array<EvidenceKey>>;
};

/**
 * ModelConfigPublic
 */
export type ModelConfigPublic = {
    /**
     * Version
     */
    version: string;
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Has Key
     */
    has_key?: boolean;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSave = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * PasswordResetEmail
 */
export type PasswordResetEmail = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RegistrationPublic
 */
export type RegistrationPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Verification Sent
     */
    verification_sent: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Invitation Code
     */
    invitation_code: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerificationRequest
 */
export type VerificationRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSaveWritable = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

export type accountsLoginData = {
    body: Body_accounts_login;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type accountsLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsLoginError = accountsLoginErrors[keyof accountsLoginErrors];

export type accountsLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type accountsLoginResponse = accountsLoginResponses[keyof accountsLoginResponses];

export type accountsMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type accountsMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsMeResponse = accountsMeResponses[keyof accountsMeResponses];

export type accountsTrainingAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/access';
};

export type accountsTrainingAccessResponses = {
    /**
     * Response Accounts-Training Access
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type accountsTrainingAccessResponse = accountsTrainingAccessResponses[keyof accountsTrainingAccessResponses];

export type accountsRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type accountsRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRegisterError = accountsRegisterErrors[keyof accountsRegisterErrors];

export type accountsRegisterResponses = {
    /**
     * Successful Response
     */
    201: RegistrationPublic;
};

export type accountsRegisterResponse = accountsRegisterResponses[keyof accountsRegisterResponses];

export type accountsInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/invitations';
};

export type accountsInvitationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsInvitationsError = accountsInvitationsErrors[keyof accountsInvitationsErrors];

export type accountsInvitationsResponses = {
    /**
     * Response Accounts-Invitations
     *
     * Successful Response
     */
    200: Array<InvitationPublic>;
};

export type accountsInvitationsResponse = accountsInvitationsResponses[keyof accountsInvitationsResponses];

export type accountsGenerateInvitationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/invitations';
};

export type accountsGenerateInvitationResponses = {
    /**
     * Successful Response
     */
    201: InvitationPublic;
};

export type accountsGenerateInvitationResponse = accountsGenerateInvitationResponses[keyof accountsGenerateInvitationResponses];

export type accountsRevokeData = {
    body?: never;
    path: {
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/api/v1/invitations/{invitation_id}/revoke';
};

export type accountsRevokeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRevokeError = accountsRevokeErrors[keyof accountsRevokeErrors];

export type accountsRevokeResponses = {
    /**
     * Successful Response
     */
    200: InvitationPublic;
};

export type accountsRevokeResponse = accountsRevokeResponses[keyof accountsRevokeResponses];

export type accountsLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout';
};

export type accountsLogoutResponses = {
    /**
     * Response Accounts-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsLogoutResponse = accountsLogoutResponses[keyof accountsLogoutResponses];

export type accountsResendVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verification-email';
};

export type accountsResendVerificationResponses = {
    /**
     * Response Accounts-Resend Verification
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResendVerificationResponse = accountsResendVerificationResponses[keyof accountsResendVerificationResponses];

export type accountsVerifyEmailData = {
    body: VerificationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verify-email';
};

export type accountsVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsVerifyEmailError = accountsVerifyEmailErrors[keyof accountsVerifyEmailErrors];

export type accountsVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsVerifyEmailResponse = accountsVerifyEmailResponses[keyof accountsVerifyEmailResponses];

export type accountsPasswordResetEmailData = {
    body: PasswordResetEmail;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/request';
};

export type accountsPasswordResetEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPasswordResetEmailError = accountsPasswordResetEmailErrors[keyof accountsPasswordResetEmailErrors];

export type accountsPasswordResetEmailResponses = {
    /**
     * Response Accounts-Password Reset Email
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type accountsPasswordResetEmailResponse = accountsPasswordResetEmailResponses[keyof accountsPasswordResetEmailResponses];

export type accountsResetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/confirm';
};

export type accountsResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsResetPasswordError = accountsResetPasswordErrors[keyof accountsResetPasswordErrors];

export type accountsResetPasswordResponses = {
    /**
     * Response Accounts-Reset Password
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResetPasswordResponse = accountsResetPasswordResponses[keyof accountsResetPasswordResponses];

export type capabilitiesReadCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/catalog';
};

export type capabilitiesReadCatalogResponses = {
    /**
     * Successful Response
     */
    200: Catalog;
};

export type capabilitiesReadCatalogResponse = capabilitiesReadCatalogResponses[keyof capabilitiesReadCatalogResponses];

export type modelconfigDeleteConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Expected Version
         */
        expected_version: string;
    };
    url: '/api/v1/model-config';
};

export type modelconfigDeleteConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigDeleteConfigError = modelconfigDeleteConfigErrors[keyof modelconfigDeleteConfigErrors];

export type modelconfigDeleteConfigResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type modelconfigDeleteConfigResponse = modelconfigDeleteConfigResponses[keyof modelconfigDeleteConfigResponses];

export type modelconfigReadConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigReadConfigResponses = {
    /**
     * Response Modelconfig-Read Config
     *
     * Successful Response
     */
    200: ModelConfigPublic | null;
};

export type modelconfigReadConfigResponse = modelconfigReadConfigResponses[keyof modelconfigReadConfigResponses];

export type modelconfigSaveConfigData = {
    body: ModelConfigSaveWritable;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigSaveConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigSaveConfigError = modelconfigSaveConfigErrors[keyof modelconfigSaveConfigErrors];

export type modelconfigSaveConfigResponses = {
    /**
     * Successful Response
     */
    200: ModelConfigPublic;
};

export type modelconfigSaveConfigResponse = modelconfigSaveConfigResponses[keyof modelconfigSaveConfigResponses];

export type healthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type healthHealthResponses = {
    /**
     * Response Health-Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthHealthResponse = healthHealthResponses[keyof healthHealthResponses];
