// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Analysis
 */
export type Analysis = {
    /**
     * Kind
     */
    kind: 'roles' | 'no_requirements' | 'clarify';
    /**
     * Message
     */
    message: string;
    /**
     * Roles
     */
    roles?: Array<Role>;
};

/**
 * AnalysisPublic
 */
export type AnalysisPublic = {
    document: Document;
    analysis: Analysis | null;
    /**
     * Evidence
     */
    evidence: Array<Array<EvidenceView>>;
};

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Topic Id
     */
    topic_id: string;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Input Text
     */
    input_text: string;
    /**
     * Expand
     */
    expand?: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * Answer
 */
export type Answer = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Value
     */
    value: number | Array<number> | string;
    /**
     * Reason
     */
    reason: string;
};

/**
 * AnswerQuote
 */
export type AnswerQuote = {
    /**
     * Input
     */
    input: 'original' | 'clarification';
    /**
     * Field
     */
    field: 'value' | 'reason';
    /**
     * Quote
     */
    quote: string;
};

/**
 * Attempt
 */
export type Attempt = {
    /**
     * Number
     */
    number: number;
    /**
     * Code
     */
    code: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens?: number | null;
    /**
     * Completion Tokens
     */
    completion_tokens?: number | null;
    /**
     * Total Tokens
     */
    total_tokens?: number | null;
};

/**
 * Background
 */
export type Background = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Boundary
     */
    boundary: string;
};

/**
 * Body_accounts-login
 */
export type Body_accounts_login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BossAccess
 */
export type BossAccess = {
    /**
     * Stage
     */
    stage: FirstStage | BossStage;
    /**
     * Points
     */
    points: number;
    /**
     * Level
     */
    level: string;
    /**
     * Can Start
     */
    can_start: boolean;
    /**
     * Run Ids
     */
    run_ids: Array<string>;
};

/**
 * BossDecision
 */
export type BossDecision = {
    /**
     * Outcome
     */
    outcome: 'practice' | 'pending_delivery' | 'no_qualified_case' | 'invalid_case' | 'system_failure' | 'unclear' | 'evidenced_fail' | 'independent_pass_candidate' | 'not_admitted' | 'disputed' | 'pending_revalidation';
    /**
     * Promote To
     */
    promote_to?: '初级程序员' | null;
    /**
     * Shortfalls
     */
    shortfalls?: Array<ConfirmedShortfall>;
    /**
     * Semantic Reliability
     */
    semantic_reliability?: 'unverified';
};

/**
 * BossPublic
 */
export type BossPublic = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Stage
     */
    stage: FirstStage | BossStage;
    /**
     * Decision
     */
    decision: BossDecision | StageDecision | null;
    /**
     * Promotion Id
     */
    promotion_id: string | null;
    /**
     * Current Level
     */
    current_level: string;
    /**
     * Points
     */
    points: number;
};

/**
 * BossStage
 */
export type BossStage = {
    /**
     * Version
     */
    version: string;
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * From Level
     */
    from_level: '初级程序员' | '中级程序员' | '高级程序员' | '牛逼程序员' | '传奇程序员' | 'AI级程序员';
    /**
     * To Level
     */
    to_level: '初级程序员' | '中级程序员' | '高级程序员' | '牛逼程序员' | '传奇程序员' | 'AI级程序员' | null;
    /**
     * Launch Points
     */
    launch_points: number;
    /**
     * Mandatory
     */
    mandatory: Array<StageJudgment>;
    /**
     * Passing Rule
     */
    passing_rule: string;
};

/**
 * BossStart
 */
export type BossStart = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Stage
     */
    expected_stage: FirstStage | BossStage;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * Capability
 */
export type Capability = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Background Id
     */
    background_id: string;
    /**
     * Levels
     */
    levels: Array<Level>;
};

/**
 * CapabilityState
 */
export type CapabilityState = {
    target: EvidenceKey;
    /**
     * Status
     */
    status?: 'unverified' | 'verified' | 'needs_consolidation';
    /**
     * Streak
     */
    streak?: number;
    /**
     * Latest Verified At
     */
    latest_verified_at?: string | null;
    /**
     * Recovery Started At Order
     */
    recovery_started_at_order?: number | null;
    /**
     * History
     */
    history?: Array<Transition>;
};

/**
 * Catalog
 */
export type Catalog = {
    /**
     * Version
     */
    version: string;
    /**
     * Quality
     */
    quality: string;
    /**
     * Difficulty Criteria
     */
    difficulty_criteria: {
        [key: string]: string;
    };
    /**
     * Backgrounds
     */
    backgrounds: Array<Background>;
    /**
     * Domains
     */
    domains: [
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain
    ];
};

/**
 * CheckStart
 */
export type CheckStart = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * Citation
 */
export type Citation = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Quote
     */
    quote: string;
};

/**
 * Clarify
 */
export type Clarify = {
    /**
     * Answers
     */
    answers?: Array<Answer> | null;
};

/**
 * CollectionView
 */
export type CollectionView = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Help Id
     */
    help_id: string | null;
    /**
     * Revision
     */
    revision: string;
    /**
     * Generation
     */
    generation: string;
    /**
     * Versions
     */
    versions: Array<DraftSnapshot>;
    /**
     * Current
     */
    current: string | null;
    /**
     * Unresolved
     */
    unresolved: Array<string>;
};

/**
 * ConceptContent
 */
export type ConceptContent = {
    /**
     * Plain
     */
    plain: string;
    /**
     * Example
     */
    example: string;
    /**
     * Relation
     */
    relation: string;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Principle
     */
    principle?: string | null;
};

/**
 * ConfirmHelp
 */
export type ConfirmHelp = {
    /**
     * Content Hash
     */
    content_hash: string;
    /**
     * Accepted
     */
    accepted: boolean;
};

/**
 * ConfirmationReceipt
 */
export type ConfirmationReceipt = {
    /**
     * Id
     */
    id: string;
};

/**
 * ConfirmedShortfall
 */
export type ConfirmedShortfall = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    target: EvidenceKey;
    /**
     * Gap
     */
    gap: string;
};

/**
 * Document
 */
export type Document = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
};

/**
 * Domain
 */
export type Domain = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Capabilities
     */
    capabilities: Array<Capability>;
    /**
     * Examples
     */
    examples: Array<Example>;
};

/**
 * DraftAnswer
 */
export type DraftAnswer = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Value
     */
    value?: number | Array<number> | string | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * DraftProgress
 */
export type DraftProgress = {
    /**
     * Answers
     */
    answers?: Array<DraftAnswer>;
    /**
     * Step
     */
    step?: 'materials' | 'judgments' | 'coach';
    /**
     * Based On Submission Id
     */
    based_on_submission_id?: string | null;
};

/**
 * DraftSnapshot
 */
export type DraftSnapshot = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Version
     */
    version: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Saved At
     */
    saved_at: string;
    progress: DraftProgress;
};

/**
 * EditRequest
 */
export type EditRequest = {
    /**
     * Expected Version
     */
    expected_version: string;
    /**
     * Operation
     */
    operation: 'edit' | 'reorder';
    /**
     * Node Id
     */
    node_id?: string | null;
    goal?: Goal | null;
    /**
     * Order
     */
    order?: Array<string> | null;
};

/**
 * EvaluationInputs
 */
export type EvaluationInputs = {
    original: InputSnapshot;
    clarification?: InputSnapshot | null;
    /**
     * Clarification Used
     */
    clarification_used: boolean;
};

/**
 * EvaluationPublic
 */
export type EvaluationPublic = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Frozen Sequence
     */
    frozen_sequence: number | null;
    /**
     * Frozen At
     */
    frozen_at: string | null;
    inputs: EvaluationInputs;
    result: GradingCandidate | null;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Can Retry
     */
    can_retry: boolean;
    /**
     * Independent Outcome
     */
    independent_outcome: string | null;
};

/**
 * EvaluationStart
 */
export type EvaluationStart = {
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
};

/**
 * Evidence
 */
export type Evidence = {
    /**
     * Kind
     */
    kind?: 'ordinary' | 'boss';
    /**
     * Original Id
     */
    original_id: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Order
     */
    order: number;
    /**
     * Submitted At
     */
    submitted_at: string;
    /**
     * Order Source
     */
    order_source: 'user_locked' | 'legacy_created_at_uuid';
    target: EvidenceKey;
    /**
     * Observation Id
     */
    observation_id: string | null;
    /**
     * Observation Sequence
     */
    observation_sequence: number | null;
    /**
     * Frozen Sequence
     */
    frozen_sequence: number | null;
    /**
     * Outcome
     */
    outcome: string;
    /**
     * Qualified Novelty
     */
    qualified_novelty: boolean;
    /**
     * Case Digest
     */
    case_digest: string | null;
    /**
     * Judgment Ids
     */
    judgment_ids: Array<string>;
    /**
     * Review Id
     */
    review_id?: string | null;
    /**
     * Review Decision
     */
    review_decision?: string | null;
    /**
     * Semantic Reliability
     */
    semantic_reliability?: 'unverified';
};

/**
 * EvidenceKey
 */
export type EvidenceKey = {
    /**
     * Capability Id
     */
    capability_id: string;
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Background Id
     */
    background_id: string;
};

/**
 * EvidenceMap
 */
export type EvidenceMap = {
    /**
     * Rule Version
     */
    rule_version?: string;
    /**
     * Semantic Reliability
     */
    semantic_reliability?: 'unverified';
    /**
     * States
     */
    states: Array<CapabilityState>;
};

/**
 * EvidenceView
 */
export type EvidenceView = {
    target: EvidenceKey | null;
    /**
     * Status
     */
    status: 'unknown' | 'unverified' | 'verified' | 'needs_consolidation';
    /**
     * Streak
     */
    streak: number | null;
    /**
     * Latest Verified At
     */
    latest_verified_at?: string | null;
    /**
     * Original Ids
     */
    original_ids?: Array<string>;
};

/**
 * Example
 */
export type Example = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Capability Ids
     */
    capability_ids: Array<string>;
    /**
     * Task
     */
    task: string;
    /**
     * Acceptable
     */
    acceptable: string;
    /**
     * Insufficient
     */
    insufficient: string;
};

/**
 * FileEntry
 */
export type FileEntry = {
    /**
     * Path
     */
    path: string;
    /**
     * Sha
     */
    sha: string;
    /**
     * Kind
     */
    kind: 'tree' | 'blob' | 'commit';
    /**
     * Mode
     */
    mode: string;
    /**
     * Size
     */
    size?: number;
};

/**
 * Finding
 */
export type Finding = {
    /**
     * Kind
     */
    kind: 'module' | 'entry' | 'call' | 'state' | 'storage';
    /**
     * Subject
     */
    subject: string;
    /**
     * Relation
     */
    relation: string;
    /**
     * Target
     */
    target: string;
    /**
     * Evidence
     */
    evidence: Array<Location>;
};

/**
 * FirstStage
 */
export type FirstStage = {
    /**
     * Version
     */
    version?: 'first-boss-v1';
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * From Level
     */
    from_level?: '小白程序员';
    /**
     * To Level
     */
    to_level?: '初级程序员';
    /**
     * Launch Points
     */
    launch_points?: 100;
    /**
     * Mandatory
     */
    mandatory: [
        MandatoryJudgment,
        MandatoryJudgment,
        MandatoryJudgment
    ];
    /**
     * Passing Rule
     */
    passing_rule: string;
};

/**
 * Fragment
 */
export type Fragment = {
    /**
     * Path
     */
    path: string;
    /**
     * Blob
     */
    blob: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Total Lines
     */
    total_lines: number;
    /**
     * Text
     */
    text: string;
};

/**
 * Goal
 */
export type Goal = {
    target: EvidenceKey;
    /**
     * Text
     */
    text: string;
    /**
     * Focus
     */
    focus: string;
};

/**
 * GradingCandidate
 */
export type GradingCandidate = {
    /**
     * Items
     */
    items: Array<GradingItem>;
};

/**
 * GradingItem
 */
export type GradingItem = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Conclusion
     */
    conclusion: 'pass' | 'evidenced_fail' | 'unclear';
    /**
     * Answer Quotes
     */
    answer_quotes: Array<AnswerQuote>;
    /**
     * Grounding
     */
    grounding: Array<Grounding>;
    /**
     * Interpreted Value
     */
    interpreted_value: number | Array<number> | string | null;
    /**
     * Interpreted Reasoning
     */
    interpreted_reasoning: number | Array<number> | string | null;
    /**
     * Reason Claims
     */
    reason_claims: Array<ReasonClaim>;
    /**
     * Rule Quote
     */
    rule_quote: string | null;
    /**
     * Counterexample Quote
     */
    counterexample_quote: string | null;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Gap
     */
    gap: string | null;
};

/**
 * Grounding
 */
export type Grounding = {
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Fact
     */
    fact: string;
    /**
     * Value
     */
    value: string;
    citation: Citation;
};

/**
 * GuidanceDraft
 */
export type GuidanceDraft = {
    /**
     * Kind
     */
    kind: 'hint' | 'demonstration';
    /**
     * Scenario Fingerprint
     */
    scenario_fingerprint: string;
    /**
     * Steps
     */
    steps: Array<GuidanceStep>;
    /**
     * Direction
     */
    direction?: 'directional';
};

/**
 * GuidanceStep
 */
export type GuidanceStep = {
    judgment: Judgment;
    /**
     * Evidence
     */
    evidence: Array<PublicEvidence>;
    solution?: WorkedAnswer | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HelpAnswer
 */
export type HelpAnswer = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Value
     */
    value?: number | Array<number> | string | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * HelpCreate
 */
export type HelpCreate = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Kind
     */
    kind?: 'concept' | 'hint' | 'demonstration';
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    input: HelpInput;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * HelpInput
 */
export type HelpInput = {
    /**
     * Question
     */
    question: string;
    /**
     * Depth
     */
    depth?: 'basic' | 'deep';
    /**
     * Answers
     */
    answers?: Array<HelpAnswer>;
};

/**
 * HelpPublic
 */
export type HelpPublic = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Id
     */
    id: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    input: HelpInput;
    /**
     * Created Sequence
     */
    created_sequence: number;
    /**
     * Generated Sequence
     */
    generated_sequence: number | null;
    /**
     * Checked Sequence
     */
    checked_sequence: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Direction
     */
    direction: string | null;
    /**
     * Requires Independent Confirmation
     */
    requires_independent_confirmation: boolean;
    /**
     * Confirmation Prompt
     */
    confirmation_prompt: string | null;
    /**
     * Content Hash
     */
    content_hash: string | null;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Deliveries
     */
    deliveries: Array<PublicDelivery>;
    /**
     * Can Retry
     */
    can_retry: boolean;
};

/**
 * HelpPublication
 */
export type HelpPublication = {
    /**
     * Help Id
     */
    help_id: string;
    /**
     * Delivery Id
     */
    delivery_id: string;
    /**
     * Receipt Token
     */
    receipt_token: string;
    /**
     * Content
     */
    content: ConceptContent | GuidanceDraft;
    /**
     * Content Hash
     */
    content_hash: string;
    /**
     * Sections
     */
    sections: {
        [key: string]: string;
    };
    /**
     * Exposure Sequence
     */
    exposure_sequence: number;
};

/**
 * InputSnapshot
 */
export type InputSnapshot = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Answers
     */
    answers: Array<Answer>;
};

/**
 * InvitationPublic
 */
export type InvitationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Status
     */
    status: 'unused' | 'used' | 'revoked';
    /**
     * Created At
     */
    created_at: string;
};

/**
 * JDPublic
 */
export type JDPublic = {
    topic: TopicPublic;
    /**
     * Documents
     */
    documents: Array<AnalysisPublic>;
    current: Route | null;
    /**
     * Evidence
     */
    evidence: Array<EvidenceView>;
    /**
     * Node Evidence
     */
    node_evidence: {
        [key: string]: EvidenceView;
    };
    /**
     * Semantic Reliability
     */
    semantic_reliability?: string;
};

/**
 * JobPublic
 */
export type JobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Topic Id
     */
    topic_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Input Text
     */
    input_text: string;
    /**
     * Result Id
     */
    result_id: string | null;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
};

/**
 * Judgment
 */
export type Judgment = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'choice' | 'order' | 'prediction';
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
};

/**
 * Level
 */
export type Level = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Required
     */
    required?: Array<EvidenceKey>;
    /**
     * Alternatives
     */
    alternatives?: Array<Array<EvidenceKey>>;
};

/**
 * Location
 */
export type Location = {
    /**
     * Path
     */
    path: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Quote
     */
    quote: string;
};

/**
 * MandatoryJudgment
 */
export type MandatoryJudgment = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Scope
     */
    scope: '请求／状态链路' | '局部因果' | '查证与验证';
    target: EvidenceKey;
};

/**
 * Mapping
 */
export type Mapping = {
    /**
     * Node Id
     */
    node_id: string;
    requirement: Requirement;
};

/**
 * ModelConfigPublic
 */
export type ModelConfigPublic = {
    /**
     * Version
     */
    version: string;
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Has Key
     */
    has_key?: boolean;
    /**
     * Revoked
     */
    revoked?: boolean;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSave = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * Node
 */
export type Node = {
    target: EvidenceKey;
    /**
     * Text
     */
    text: string;
    /**
     * Focus
     */
    focus: string;
    /**
     * Id
     */
    id: string;
};

/**
 * Observation
 */
export type Observation = {
    /**
     * Id
     */
    id: string;
    /**
     * Requirement
     */
    requirement: string;
    /**
     * Source Capability
     */
    source_capability: string;
};

/**
 * Opinion
 */
export type Opinion = {
    /**
     * Decision
     */
    decision: 'upheld' | 'corrected' | 'disputed';
    /**
     * Explanation
     */
    explanation: string;
    grading: GradingCandidate | null;
};

/**
 * PasswordResetEmail
 */
export type PasswordResetEmail = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PracticeCase
 */
export type PracticeCase = {
    /**
     * Kind
     */
    kind?: 'same_scenario_practice';
    /**
     * Scenario Fingerprint
     */
    scenario_fingerprint: string;
    case: PublicCase;
    /**
     * Instructions
     */
    instructions?: string;
};

/**
 * PracticeState
 */
export type PracticeState = {
    /**
     * Help Id
     */
    help_id: string;
    exercise: PracticeCase;
    records: SubmissionState;
    /**
     * Completed
     */
    completed: boolean;
};

/**
 * PreferencePublic
 */
export type PreferencePublic = {
    /**
     * Version
     */
    version: string | null;
    /**
     * Mode
     */
    mode: 'recommended' | '基础' | '进阶' | '综合';
    /**
     * Has Record
     */
    has_record: boolean;
};

/**
 * PreferenceUpdate
 */
export type PreferenceUpdate = {
    /**
     * Expected Version
     */
    expected_version: string | null;
    /**
     * Mode
     */
    mode: 'recommended' | '基础' | '进阶' | '综合';
};

/**
 * ProbeInput
 */
export type ProbeInput = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id?: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * ProbeResult
 */
export type ProbeResult = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Models
     */
    models?: Array<string>;
    /**
     * Attempts
     */
    attempts?: Array<Attempt>;
};

/**
 * ProjectMap
 */
export type ProjectMap = {
    /**
     * Confirmed
     */
    confirmed?: Array<Finding>;
    /**
     * Unverified
     */
    unverified?: Array<Finding>;
    /**
     * Missing
     */
    missing?: Array<string>;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Reused From Id
     */
    reused_from_id: string | null;
    snapshot: Snapshot | null;
    project_map: ProjectMap | null;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
};

/**
 * ProjectStart
 */
export type ProjectStart = {
    /**
     * Url
     */
    url: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Reanalyze
     */
    reanalyze?: boolean;
};

/**
 * PublicCase
 */
export type PublicCase = {
    target: EvidenceKey;
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * Title
     */
    title: string;
    /**
     * Task
     */
    task: string;
    /**
     * Assumptions
     */
    assumptions: Array<string>;
    /**
     * Evidence
     */
    evidence: Array<PublicEvidence>;
    /**
     * Judgments
     */
    judgments: Array<Judgment>;
    /**
     * Sources
     */
    sources: Array<Source>;
    /**
     * Quality
     */
    quality?: string;
};

/**
 * PublicDelivery
 */
export type PublicDelivery = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Exposure Sequence
     */
    exposure_sequence: number;
    /**
     * Attempt Id
     */
    attempt_id: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Delivered Text
     */
    delivered_text: string;
    /**
     * Direction
     */
    direction: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Evidence
     */
    evidence: string;
};

/**
 * PublicEvidence
 */
export type PublicEvidence = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: '教学材料';
    /**
     * Text
     */
    text: string;
    /**
     * Citations
     */
    citations: Array<Citation>;
};

/**
 * PublicationChoice
 */
export type PublicationChoice = {
    /**
     * Confirmation Id
     */
    confirmation_id?: string | null;
};

/**
 * Quote
 */
export type Quote = {
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Text
     */
    text: string;
};

/**
 * ReasonClaim
 */
export type ReasonClaim = {
    /**
     * Answer Quote
     */
    answer_quote: number;
    /**
     * Grounding
     */
    grounding: number;
    /**
     * Interpreted Fact Value
     */
    interpreted_fact_value: string;
};

/**
 * RegistrationPublic
 */
export type RegistrationPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Verification Sent
     */
    verification_sent: boolean;
};

/**
 * RelevanceItem
 */
export type RelevanceItem = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Status
     */
    status: 'related' | 'unrelated' | 'unclear';
};

/**
 * RenderingReceipt
 */
export type RenderingReceipt = {
    /**
     * Token
     */
    token: string;
};

/**
 * Repository
 */
export type Repository = {
    /**
     * Owner
     */
    owner: string;
    /**
     * Name
     */
    name: string;
    /**
     * Commit
     */
    commit: string;
    /**
     * Tree
     */
    tree: string;
    /**
     * Ref
     */
    ref: string;
    /**
     * Focus
     */
    focus?: string;
    /**
     * Start Line
     */
    start_line?: number;
    /**
     * End Line
     */
    end_line?: number | null;
};

/**
 * Requirement
 */
export type Requirement = {
    quote: Quote;
    /**
     * Basis
     */
    basis: 'explicit' | 'inferred';
    /**
     * Explanation
     */
    explanation: string;
    goal: Goal | null;
};

/**
 * ReviewCall
 */
export type ReviewCall = {
    /**
     * Number
     */
    number: number;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number | null;
    /**
     * Completion Tokens
     */
    completion_tokens: number | null;
    /**
     * Total Tokens
     */
    total_tokens: number | null;
};

/**
 * ReviewPublic
 */
export type ReviewPublic = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Decision
     */
    decision: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Accepted At
     */
    accepted_at: string;
    opinion: Opinion | null;
    /**
     * Attempts
     */
    attempts: Array<ReviewCall>;
    /**
     * Remaining Attempts
     */
    remaining_attempts: number;
};

/**
 * ReviewResume
 */
export type ReviewResume = {
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
};

/**
 * ReviewStart
 */
export type ReviewStart = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
};

/**
 * Role
 */
export type Role = {
    /**
     * Name
     */
    name: string;
    quote: Quote;
    /**
     * Requirements
     */
    requirements: Array<Requirement>;
};

/**
 * Route
 */
export type Route = {
    document: Document;
    /**
     * Role Name
     */
    role_name: string;
    role_quote: Quote;
    /**
     * Requirements
     */
    requirements: Array<Requirement>;
    /**
     * Mappings
     */
    mappings: Array<Mapping>;
    route: Version;
};

/**
 * SelectRequest
 */
export type SelectRequest = {
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Role Index
     */
    role_index: number;
};

/**
 * Snapshot
 */
export type Snapshot = {
    repository: Repository;
    /**
     * Entries
     */
    entries?: Array<FileEntry>;
    /**
     * Fragments
     */
    fragments?: Array<Fragment>;
    /**
     * Excluded
     */
    excluded?: {
        [key: string]: string;
    };
    /**
     * Directories
     */
    directories?: Array<FileEntry>;
    /**
     * Files
     */
    files?: Array<FileEntry>;
    /**
     * Offsets
     */
    offsets?: {
        [key: string]: number;
    };
    /**
     * Requests
     */
    requests?: number;
    /**
     * Bytes
     */
    bytes?: number;
    /**
     * Listing Complete
     */
    listing_complete?: boolean;
};

/**
 * Source
 */
export type Source = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Version
     */
    version: string;
    /**
     * Locator
     */
    locator: string;
    /**
     * Text
     */
    text: string;
};

/**
 * StageDecision
 */
export type StageDecision = {
    /**
     * Outcome
     */
    outcome: 'practice' | 'pending_delivery' | 'no_qualified_case' | 'invalid_case' | 'system_failure' | 'unclear' | 'evidenced_fail' | 'independent_pass_candidate' | 'not_admitted' | 'disputed' | 'pending_revalidation';
    /**
     * Promote To
     */
    promote_to?: '初级程序员' | '中级程序员' | '高级程序员' | '牛逼程序员' | '传奇程序员' | 'AI级程序员' | null;
    /**
     * Shortfalls
     */
    shortfalls?: Array<ConfirmedShortfall>;
    /**
     * Semantic Reliability
     */
    semantic_reliability?: 'unverified';
};

/**
 * StageJudgment
 */
export type StageJudgment = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Scope
     */
    scope: string;
    target: EvidenceKey;
    /**
     * Observations
     */
    observations: Array<Observation>;
};

/**
 * Start
 */
export type Start = {
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Previous Run Id
     */
    previous_run_id?: string | null;
    /**
     * Request Id
     */
    request_id?: string | null;
    /**
     * Expected Preference Version
     */
    expected_preference_version?: string | null;
};

/**
 * StartRequest
 */
export type StartRequest = {
    /**
     * Expected Version
     */
    expected_version: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * StartSnapshot
 */
export type StartSnapshot = {
    target: EvidenceKey;
    /**
     * Text
     */
    text: string;
    /**
     * Focus
     */
    focus: string;
    /**
     * Version Id
     */
    version_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Catalog Version
     */
    catalog_version: string;
};

/**
 * SubmissionPublic
 */
export type SubmissionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Original Id
     */
    original_id: string | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Answers
     */
    answers: Array<Answer>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Relevance
     */
    relevance: Array<RelevanceItem>;
    /**
     * Neutral Clarification
     */
    neutral_clarification: boolean;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Can Retry
     */
    can_retry: boolean;
};

/**
 * SubmissionState
 */
export type SubmissionState = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Submissions
     */
    submissions: Array<SubmissionPublic>;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Awarded Points
     */
    awarded_points: number;
    /**
     * Total Points
     */
    total_points: number;
    /**
     * Rule Version
     */
    rule_version: string | null;
};

/**
 * Submit
 */
export type Submit = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Evaluate After Submit
     */
    evaluate_after_submit?: boolean;
    /**
     * Answers
     */
    answers: Array<Answer>;
    /**
     * Previous Submission Id
     */
    previous_submission_id?: string | null;
};

/**
 * TargetStart
 */
export type TargetStart = {
    target: EvidenceKey;
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Mode
     */
    mode: 'practice' | 'independent';
    return_target?: EvidenceKey | null;
};

/**
 * TaskPublic
 */
export type TaskPublic = {
    topic_snapshot?: StartSnapshot | null;
    /**
     * Jd Simulation
     */
    jd_simulation?: {
        [key: string]: string;
    } | null;
    /**
     * Boss Stage
     */
    boss_stage?: FirstStage | BossStage | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    target: EvidenceKey;
    /**
     * Goal
     */
    goal: string;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    case: PublicCase | null;
    /**
     * Launch Mode
     */
    launch_mode: string;
    /**
     * Current Mode
     */
    current_mode: string;
    /**
     * Origin Id
     */
    origin_id: string | null;
    /**
     * Independent Outcome
     */
    independent_outcome: string | null;
    return_target?: EvidenceKey | null;
    /**
     * Recommendation Reason
     */
    recommendation_reason?: string | null;
    /**
     * Random Mode
     */
    random_mode?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TokenTotal
 */
export type TokenTotal = {
    /**
     * Known
     */
    known: number;
    /**
     * Unknown Calls
     */
    unknown_calls: number;
};

/**
 * TopicPublic
 */
export type TopicPublic = {
    /**
     * Id
     */
    id: string;
    current: Version | null;
    /**
     * Active Id
     */
    active_id: string | null;
    /**
     * Versions
     */
    versions: Array<Version>;
    /**
     * Jobs
     */
    jobs: Array<JobPublic>;
    /**
     * Runs
     */
    runs: Array<TaskPublic>;
    /**
     * Completed Node Ids
     */
    completed_node_ids: Array<string>;
};

/**
 * Transition
 */
export type Transition = {
    evidence: Evidence;
    /**
     * Status
     */
    status: 'unverified' | 'verified' | 'needs_consolidation';
    /**
     * Streak
     */
    streak: number;
    /**
     * Counted
     */
    counted: boolean;
};

/**
 * UnitAccess
 */
export type UnitAccess = {
    target: EvidenceKey;
    /**
     * Catalog Version
     */
    catalog_version?: string;
    /**
     * Opened
     */
    opened: boolean;
    /**
     * Eligible
     */
    eligible: boolean;
    /**
     * Missing Required
     */
    missing_required: Array<EvidenceKey>;
    /**
     * Missing Alternatives
     */
    missing_alternatives: Array<Array<EvidenceKey>>;
};

/**
 * UnitRequest
 */
export type UnitRequest = {
    target: EvidenceKey;
    /**
     * Catalog Version
     */
    catalog_version: string;
};

/**
 * UsageCall
 */
export type UsageCall = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Config Version
     */
    config_version: string | null;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Number
     */
    number: number;
    /**
     * Code
     */
    code: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number | null;
    /**
     * Completion Tokens
     */
    completion_tokens: number | null;
    /**
     * Total Tokens
     */
    total_tokens: number | null;
};

/**
 * UsageReport
 */
export type UsageReport = {
    /**
     * Calls
     */
    calls: Array<UsageCall>;
    /**
     * Totals
     */
    totals: {
        [key: string]: TokenTotal;
    };
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Invitation Code
     */
    invitation_code: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerificationRequest
 */
export type VerificationRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * Version
 *
 * Trusted stored snapshot, never a request/model response schema.
 */
export type Version = {
    /**
     * Id
     */
    id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * Input Text
     */
    input_text: string;
    /**
     * Kind
     */
    kind: 'non_engineering' | 'clear' | 'broad' | 'clarify';
    /**
     * Message
     */
    message: string;
    /**
     * Nodes
     */
    nodes: Array<Node>;
    /**
     * Recommended Id
     */
    recommended_id: string | null;
    /**
     * Confirmed
     */
    confirmed?: boolean;
};

/**
 * VersionChoice
 */
export type VersionChoice = {
    /**
     * Observed Revision
     */
    observed_revision: string;
    /**
     * Version
     */
    version: string;
};

/**
 * VersionReceipt
 */
export type VersionReceipt = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Version
     */
    version: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Saved At
     */
    saved_at: string;
    progress: DraftProgress;
    /**
     * Revision
     */
    revision: string;
    /**
     * Generation
     */
    generation: string;
};

/**
 * VersionRequest
 */
export type VersionRequest = {
    /**
     * Expected Version
     */
    expected_version: string;
};

/**
 * VersionWrite
 */
export type VersionWrite = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Version
     */
    expected_version: string | null;
    progress: DraftProgress;
    /**
     * Observed Revision
     */
    observed_revision: string;
    /**
     * Generation
     */
    generation: string;
};

/**
 * WorkedAnswer
 */
export type WorkedAnswer = {
    /**
     * Acceptable Values
     */
    acceptable_values: Array<number | Array<number> | string>;
    /**
     * Reasoning
     */
    reasoning: string;
    /**
     * Counterexample
     */
    counterexample: string;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSaveWritable = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * ProbeInput
 */
export type ProbeInputWritable = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id?: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

export type accountsLoginData = {
    body: Body_accounts_login;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type accountsLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsLoginError = accountsLoginErrors[keyof accountsLoginErrors];

export type accountsLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type accountsLoginResponse = accountsLoginResponses[keyof accountsLoginResponses];

export type accountsMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type accountsMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsMeResponse = accountsMeResponses[keyof accountsMeResponses];

export type accountsTrainingAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/access';
};

export type accountsTrainingAccessResponses = {
    /**
     * Response Accounts-Training Access
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type accountsTrainingAccessResponse = accountsTrainingAccessResponses[keyof accountsTrainingAccessResponses];

export type accountsRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type accountsRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRegisterError = accountsRegisterErrors[keyof accountsRegisterErrors];

export type accountsRegisterResponses = {
    /**
     * Successful Response
     */
    201: RegistrationPublic;
};

export type accountsRegisterResponse = accountsRegisterResponses[keyof accountsRegisterResponses];

export type accountsInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/invitations';
};

export type accountsInvitationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsInvitationsError = accountsInvitationsErrors[keyof accountsInvitationsErrors];

export type accountsInvitationsResponses = {
    /**
     * Response Accounts-Invitations
     *
     * Successful Response
     */
    200: Array<InvitationPublic>;
};

export type accountsInvitationsResponse = accountsInvitationsResponses[keyof accountsInvitationsResponses];

export type accountsGenerateInvitationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/invitations';
};

export type accountsGenerateInvitationResponses = {
    /**
     * Successful Response
     */
    201: InvitationPublic;
};

export type accountsGenerateInvitationResponse = accountsGenerateInvitationResponses[keyof accountsGenerateInvitationResponses];

export type accountsRevokeData = {
    body?: never;
    path: {
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/api/v1/invitations/{invitation_id}/revoke';
};

export type accountsRevokeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRevokeError = accountsRevokeErrors[keyof accountsRevokeErrors];

export type accountsRevokeResponses = {
    /**
     * Successful Response
     */
    200: InvitationPublic;
};

export type accountsRevokeResponse = accountsRevokeResponses[keyof accountsRevokeResponses];

export type accountsLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout';
};

export type accountsLogoutResponses = {
    /**
     * Response Accounts-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsLogoutResponse = accountsLogoutResponses[keyof accountsLogoutResponses];

export type accountsResendVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verification-email';
};

export type accountsResendVerificationResponses = {
    /**
     * Response Accounts-Resend Verification
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResendVerificationResponse = accountsResendVerificationResponses[keyof accountsResendVerificationResponses];

export type accountsVerifyEmailData = {
    body: VerificationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verify-email';
};

export type accountsVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsVerifyEmailError = accountsVerifyEmailErrors[keyof accountsVerifyEmailErrors];

export type accountsVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsVerifyEmailResponse = accountsVerifyEmailResponses[keyof accountsVerifyEmailResponses];

export type accountsPasswordResetEmailData = {
    body: PasswordResetEmail;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/request';
};

export type accountsPasswordResetEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPasswordResetEmailError = accountsPasswordResetEmailErrors[keyof accountsPasswordResetEmailErrors];

export type accountsPasswordResetEmailResponses = {
    /**
     * Response Accounts-Password Reset Email
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type accountsPasswordResetEmailResponse = accountsPasswordResetEmailResponses[keyof accountsPasswordResetEmailResponses];

export type accountsResetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/confirm';
};

export type accountsResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsResetPasswordError = accountsResetPasswordErrors[keyof accountsResetPasswordErrors];

export type accountsResetPasswordResponses = {
    /**
     * Response Accounts-Reset Password
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResetPasswordResponse = accountsResetPasswordResponses[keyof accountsResetPasswordResponses];

export type capabilitiesReadCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/catalog';
};

export type capabilitiesReadCatalogResponses = {
    /**
     * Successful Response
     */
    200: Catalog;
};

export type capabilitiesReadCatalogResponse = capabilitiesReadCatalogResponses[keyof capabilitiesReadCatalogResponses];

export type capabilitiesReadCapabilityEvidenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/evidence';
};

export type capabilitiesReadCapabilityEvidenceResponses = {
    /**
     * Successful Response
     */
    200: EvidenceMap;
};

export type capabilitiesReadCapabilityEvidenceResponse = capabilitiesReadCapabilityEvidenceResponses[keyof capabilitiesReadCapabilityEvidenceResponses];

export type capabilitiesReadUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/access';
};

export type capabilitiesReadUnitsResponses = {
    /**
     * Response Capabilities-Read Units
     *
     * Successful Response
     */
    200: Array<UnitAccess>;
};

export type capabilitiesReadUnitsResponse = capabilitiesReadUnitsResponses[keyof capabilitiesReadUnitsResponses];

export type capabilitiesOpenLearningUnitData = {
    body: UnitRequest;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/open';
};

export type capabilitiesOpenLearningUnitErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type capabilitiesOpenLearningUnitError = capabilitiesOpenLearningUnitErrors[keyof capabilitiesOpenLearningUnitErrors];

export type capabilitiesOpenLearningUnitResponses = {
    /**
     * Successful Response
     */
    200: UnitAccess;
};

export type capabilitiesOpenLearningUnitResponse = capabilitiesOpenLearningUnitResponses[keyof capabilitiesOpenLearningUnitResponses];

export type capabilitiesStartTargetData = {
    body: TargetStart;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/start';
};

export type capabilitiesStartTargetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type capabilitiesStartTargetError = capabilitiesStartTargetErrors[keyof capabilitiesStartTargetErrors];

export type capabilitiesStartTargetResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type capabilitiesStartTargetResponse = capabilitiesStartTargetResponses[keyof capabilitiesStartTargetResponses];

export type modelconfigDeleteConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Expected Version
         */
        expected_version: string;
    };
    url: '/api/v1/model-config';
};

export type modelconfigDeleteConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigDeleteConfigError = modelconfigDeleteConfigErrors[keyof modelconfigDeleteConfigErrors];

export type modelconfigDeleteConfigResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type modelconfigDeleteConfigResponse = modelconfigDeleteConfigResponses[keyof modelconfigDeleteConfigResponses];

export type modelconfigReadConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigReadConfigResponses = {
    /**
     * Response Modelconfig-Read Config
     *
     * Successful Response
     */
    200: ModelConfigPublic | null;
};

export type modelconfigReadConfigResponse = modelconfigReadConfigResponses[keyof modelconfigReadConfigResponses];

export type modelconfigSaveConfigData = {
    body: ModelConfigSaveWritable;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigSaveConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigSaveConfigError = modelconfigSaveConfigErrors[keyof modelconfigSaveConfigErrors];

export type modelconfigSaveConfigResponses = {
    /**
     * Successful Response
     */
    200: ModelConfigPublic;
};

export type modelconfigSaveConfigResponse = modelconfigSaveConfigResponses[keyof modelconfigSaveConfigResponses];

export type modelconfigReadUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/model-config/usage';
};

export type modelconfigReadUsageResponses = {
    /**
     * Successful Response
     */
    200: UsageReport;
};

export type modelconfigReadUsageResponse = modelconfigReadUsageResponses[keyof modelconfigReadUsageResponses];

export type modelconfigProbeData = {
    body: ProbeInputWritable;
    path: {
        /**
         * Kind
         */
        kind: 'test' | 'models';
    };
    query?: never;
    url: '/api/v1/model-config/probe/{kind}';
};

export type modelconfigProbeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigProbeError = modelconfigProbeErrors[keyof modelconfigProbeErrors];

export type modelconfigProbeResponses = {
    /**
     * Successful Response
     */
    200: ProbeResult;
};

export type modelconfigProbeResponse = modelconfigProbeResponses[keyof modelconfigProbeResponses];

export type trainingReadPreferenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/random-preference';
};

export type trainingReadPreferenceResponses = {
    /**
     * Successful Response
     */
    200: PreferencePublic;
};

export type trainingReadPreferenceResponse = trainingReadPreferenceResponses[keyof trainingReadPreferenceResponses];

export type trainingSavePreferenceData = {
    body: PreferenceUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/training/random-preference';
};

export type trainingSavePreferenceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingSavePreferenceError = trainingSavePreferenceErrors[keyof trainingSavePreferenceErrors];

export type trainingSavePreferenceResponses = {
    /**
     * Successful Response
     */
    200: PreferencePublic;
};

export type trainingSavePreferenceResponse = trainingSavePreferenceResponses[keyof trainingSavePreferenceResponses];

export type trainingStartData = {
    body: Start;
    path?: never;
    query?: never;
    url: '/api/v1/training/random';
};

export type trainingStartErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingStartError = trainingStartErrors[keyof trainingStartErrors];

export type trainingStartResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type trainingStartResponse = trainingStartResponses[keyof trainingStartResponses];

export type trainingLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/tasks';
};

export type trainingLatestResponses = {
    /**
     * Response Training-Latest
     *
     * Successful Response
     */
    200: Array<TaskPublic>;
};

export type trainingLatestResponse = trainingLatestResponses[keyof trainingLatestResponses];

export type trainingReadData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}';
};

export type trainingReadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingReadError = trainingReadErrors[keyof trainingReadErrors];

export type trainingReadResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type trainingReadResponse = trainingReadResponses[keyof trainingReadResponses];

export type trainingStopData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/stop';
};

export type trainingStopErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingStopError = trainingStopErrors[keyof trainingStopErrors];

export type trainingStopResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type trainingStopResponse = trainingStopResponses[keyof trainingStopResponses];

export type submissionsReadSubmissionsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions';
};

export type submissionsReadSubmissionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsReadSubmissionsError = submissionsReadSubmissionsErrors[keyof submissionsReadSubmissionsErrors];

export type submissionsReadSubmissionsResponses = {
    /**
     * Successful Response
     */
    200: SubmissionState;
};

export type submissionsReadSubmissionsResponse = submissionsReadSubmissionsResponses[keyof submissionsReadSubmissionsResponses];

export type submissionsSubmitData = {
    body: Submit;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions';
};

export type submissionsSubmitErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsSubmitError = submissionsSubmitErrors[keyof submissionsSubmitErrors];

export type submissionsSubmitResponses = {
    /**
     * Successful Response
     */
    202: SubmissionState;
};

export type submissionsSubmitResponse = submissionsSubmitResponses[keyof submissionsSubmitResponses];

export type submissionsRetrySubmissionData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions/{submission_id}/retry';
};

export type submissionsRetrySubmissionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsRetrySubmissionError = submissionsRetrySubmissionErrors[keyof submissionsRetrySubmissionErrors];

export type submissionsRetrySubmissionResponses = {
    /**
     * Successful Response
     */
    202: SubmissionState;
};

export type submissionsRetrySubmissionResponse = submissionsRetrySubmissionResponses[keyof submissionsRetrySubmissionResponses];

export type submissionsStopSubmissionData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions/{submission_id}/stop';
};

export type submissionsStopSubmissionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsStopSubmissionError = submissionsStopSubmissionErrors[keyof submissionsStopSubmissionErrors];

export type submissionsStopSubmissionResponses = {
    /**
     * Successful Response
     */
    200: SubmissionState;
};

export type submissionsStopSubmissionResponse = submissionsStopSubmissionResponses[keyof submissionsStopSubmissionResponses];

export type projectsLatestProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type projectsLatestProjectsResponses = {
    /**
     * Response Projects-Latest Projects
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type projectsLatestProjectsResponse = projectsLatestProjectsResponses[keyof projectsLatestProjectsResponses];

export type projectsStartProjectData = {
    body: ProjectStart;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type projectsStartProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsStartProjectError = projectsStartProjectErrors[keyof projectsStartProjectErrors];

export type projectsStartProjectResponses = {
    /**
     * Successful Response
     */
    202: ProjectPublic;
};

export type projectsStartProjectResponse = projectsStartProjectResponses[keyof projectsStartProjectResponses];

export type projectsReadProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}';
};

export type projectsReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsReadProjectError = projectsReadProjectErrors[keyof projectsReadProjectErrors];

export type projectsReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsReadProjectResponse = projectsReadProjectResponses[keyof projectsReadProjectResponses];

export type projectsRetryProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}/retry';
};

export type projectsRetryProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsRetryProjectError = projectsRetryProjectErrors[keyof projectsRetryProjectErrors];

export type projectsRetryProjectResponses = {
    /**
     * Successful Response
     */
    202: ProjectPublic;
};

export type projectsRetryProjectResponse = projectsRetryProjectResponses[keyof projectsRetryProjectResponses];

export type projectsStopProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}/stop';
};

export type projectsStopProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsStopProjectError = projectsStopProjectErrors[keyof projectsStopProjectErrors];

export type projectsStopProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsStopProjectResponse = projectsStopProjectResponses[keyof projectsStopProjectResponses];

export type evaluationsReadEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation';
};

export type evaluationsReadEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsReadEvaluationError = evaluationsReadEvaluationErrors[keyof evaluationsReadEvaluationErrors];

export type evaluationsReadEvaluationResponses = {
    /**
     * Response Evaluations-Read Evaluation
     *
     * Successful Response
     */
    200: EvaluationPublic | null;
};

export type evaluationsReadEvaluationResponse = evaluationsReadEvaluationResponses[keyof evaluationsReadEvaluationResponses];

export type evaluationsStartEvaluationData = {
    body: EvaluationStart;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation';
};

export type evaluationsStartEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsStartEvaluationError = evaluationsStartEvaluationErrors[keyof evaluationsStartEvaluationErrors];

export type evaluationsStartEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsStartEvaluationResponse = evaluationsStartEvaluationResponses[keyof evaluationsStartEvaluationResponses];

export type evaluationsClarifyEvaluationData = {
    body: Clarify;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/clarification';
};

export type evaluationsClarifyEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsClarifyEvaluationError = evaluationsClarifyEvaluationErrors[keyof evaluationsClarifyEvaluationErrors];

export type evaluationsClarifyEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsClarifyEvaluationResponse = evaluationsClarifyEvaluationResponses[keyof evaluationsClarifyEvaluationResponses];

export type evaluationsRetryEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/retry';
};

export type evaluationsRetryEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsRetryEvaluationError = evaluationsRetryEvaluationErrors[keyof evaluationsRetryEvaluationErrors];

export type evaluationsRetryEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsRetryEvaluationResponse = evaluationsRetryEvaluationResponses[keyof evaluationsRetryEvaluationResponses];

export type evaluationsStopEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/stop';
};

export type evaluationsStopEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsStopEvaluationError = evaluationsStopEvaluationErrors[keyof evaluationsStopEvaluationErrors];

export type evaluationsStopEvaluationResponses = {
    /**
     * Successful Response
     */
    200: EvaluationPublic;
};

export type evaluationsStopEvaluationResponse = evaluationsStopEvaluationResponses[keyof evaluationsStopEvaluationResponses];

export type conceptsListHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help';
};

export type conceptsListHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsListHelpError = conceptsListHelpErrors[keyof conceptsListHelpErrors];

export type conceptsListHelpResponses = {
    /**
     * Response Concepts-List Help
     *
     * Successful Response
     */
    200: Array<HelpPublic>;
};

export type conceptsListHelpResponse = conceptsListHelpResponses[keyof conceptsListHelpResponses];

export type conceptsRequestHelpData = {
    body: HelpCreate;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help';
};

export type conceptsRequestHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsRequestHelpError = conceptsRequestHelpErrors[keyof conceptsRequestHelpErrors];

export type conceptsRequestHelpResponses = {
    /**
     * Successful Response
     */
    202: HelpPublic;
};

export type conceptsRequestHelpResponse = conceptsRequestHelpResponses[keyof conceptsRequestHelpResponses];

export type conceptsRetryHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/retry';
};

export type conceptsRetryHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsRetryHelpError = conceptsRetryHelpErrors[keyof conceptsRetryHelpErrors];

export type conceptsRetryHelpResponses = {
    /**
     * Successful Response
     */
    202: HelpPublic;
};

export type conceptsRetryHelpResponse = conceptsRetryHelpResponses[keyof conceptsRetryHelpResponses];

export type conceptsStopHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/stop';
};

export type conceptsStopHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsStopHelpError = conceptsStopHelpErrors[keyof conceptsStopHelpErrors];

export type conceptsStopHelpResponses = {
    /**
     * Successful Response
     */
    200: HelpPublic;
};

export type conceptsStopHelpResponse = conceptsStopHelpResponses[keyof conceptsStopHelpResponses];

export type conceptsConfirmHelpData = {
    body: ConfirmHelp;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/confirm';
};

export type conceptsConfirmHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsConfirmHelpError = conceptsConfirmHelpErrors[keyof conceptsConfirmHelpErrors];

export type conceptsConfirmHelpResponses = {
    /**
     * Successful Response
     */
    200: ConfirmationReceipt;
};

export type conceptsConfirmHelpResponse = conceptsConfirmHelpResponses[keyof conceptsConfirmHelpResponses];

export type conceptsPublishHelpData = {
    /**
     * Body
     */
    body?: PublicationChoice | null;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/deliver';
};

export type conceptsPublishHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsPublishHelpError = conceptsPublishHelpErrors[keyof conceptsPublishHelpErrors];

export type conceptsPublishHelpResponses = {
    /**
     * Successful Response
     */
    200: HelpPublication;
};

export type conceptsPublishHelpResponse = conceptsPublishHelpResponses[keyof conceptsPublishHelpResponses];

export type conceptsConfirmRenderingData = {
    body: RenderingReceipt;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
        /**
         * Delivery Id
         */
        delivery_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/deliveries/{delivery_id}/receipt';
};

export type conceptsConfirmRenderingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsConfirmRenderingError = conceptsConfirmRenderingErrors[keyof conceptsConfirmRenderingErrors];

export type conceptsConfirmRenderingResponses = {
    /**
     * Successful Response
     */
    200: HelpPublic;
};

export type conceptsConfirmRenderingResponse = conceptsConfirmRenderingResponses[keyof conceptsConfirmRenderingResponses];

export type draftsDeleteDraftData = {
    body: VersionChoice;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/draft';
};

export type draftsDeleteDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type draftsDeleteDraftError = draftsDeleteDraftErrors[keyof draftsDeleteDraftErrors];

export type draftsDeleteDraftResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type draftsDeleteDraftResponse = draftsDeleteDraftResponses[keyof draftsDeleteDraftResponses];

export type draftsReadDraftData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/draft';
};

export type draftsReadDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type draftsReadDraftError = draftsReadDraftErrors[keyof draftsReadDraftErrors];

export type draftsReadDraftResponses = {
    /**
     * Response Drafts-Read Draft
     *
     * Successful Response
     */
    200: DraftSnapshot | null;
};

export type draftsReadDraftResponse = draftsReadDraftResponses[keyof draftsReadDraftResponses];

export type draftsSaveDraftData = {
    body: VersionWrite;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/draft';
};

export type draftsSaveDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type draftsSaveDraftError = draftsSaveDraftErrors[keyof draftsSaveDraftErrors];

export type draftsSaveDraftResponses = {
    /**
     * Successful Response
     */
    200: VersionReceipt;
};

export type draftsSaveDraftResponse = draftsSaveDraftResponses[keyof draftsSaveDraftResponses];

export type draftsReadVersionsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/draft/versions';
};

export type draftsReadVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type draftsReadVersionsError = draftsReadVersionsErrors[keyof draftsReadVersionsErrors];

export type draftsReadVersionsResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type draftsReadVersionsResponse = draftsReadVersionsResponses[keyof draftsReadVersionsResponses];

export type draftsChooseDraftData = {
    body: VersionChoice;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/draft/choose';
};

export type draftsChooseDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type draftsChooseDraftError = draftsChooseDraftErrors[keyof draftsChooseDraftErrors];

export type draftsChooseDraftResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type draftsChooseDraftResponse = draftsChooseDraftResponses[keyof draftsChooseDraftResponses];

export type practiceReadPracticeData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice';
};

export type practiceReadPracticeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceReadPracticeError = practiceReadPracticeErrors[keyof practiceReadPracticeErrors];

export type practiceReadPracticeResponses = {
    /**
     * Successful Response
     */
    200: PracticeState;
};

export type practiceReadPracticeResponse = practiceReadPracticeResponses[keyof practiceReadPracticeResponses];

export type practiceSubmitPracticeData = {
    body: Submit;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice';
};

export type practiceSubmitPracticeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceSubmitPracticeError = practiceSubmitPracticeErrors[keyof practiceSubmitPracticeErrors];

export type practiceSubmitPracticeResponses = {
    /**
     * Successful Response
     */
    202: PracticeState;
};

export type practiceSubmitPracticeResponse = practiceSubmitPracticeResponses[keyof practiceSubmitPracticeResponses];

export type practiceRetryPracticeData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/{submission_id}/retry';
};

export type practiceRetryPracticeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceRetryPracticeError = practiceRetryPracticeErrors[keyof practiceRetryPracticeErrors];

export type practiceRetryPracticeResponses = {
    /**
     * Successful Response
     */
    202: PracticeState;
};

export type practiceRetryPracticeResponse = practiceRetryPracticeResponses[keyof practiceRetryPracticeResponses];

export type practiceStopPracticeData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/{submission_id}/stop';
};

export type practiceStopPracticeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceStopPracticeError = practiceStopPracticeErrors[keyof practiceStopPracticeErrors];

export type practiceStopPracticeResponses = {
    /**
     * Successful Response
     */
    200: PracticeState;
};

export type practiceStopPracticeResponse = practiceStopPracticeResponses[keyof practiceStopPracticeResponses];

export type practiceDeletePracticeDraftData = {
    body: VersionChoice;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/draft';
};

export type practiceDeletePracticeDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceDeletePracticeDraftError = practiceDeletePracticeDraftErrors[keyof practiceDeletePracticeDraftErrors];

export type practiceDeletePracticeDraftResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type practiceDeletePracticeDraftResponse = practiceDeletePracticeDraftResponses[keyof practiceDeletePracticeDraftResponses];

export type practiceReadPracticeDraftData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/draft';
};

export type practiceReadPracticeDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceReadPracticeDraftError = practiceReadPracticeDraftErrors[keyof practiceReadPracticeDraftErrors];

export type practiceReadPracticeDraftResponses = {
    /**
     * Response Practice-Read Practice Draft
     *
     * Successful Response
     */
    200: DraftSnapshot | null;
};

export type practiceReadPracticeDraftResponse = practiceReadPracticeDraftResponses[keyof practiceReadPracticeDraftResponses];

export type practiceSavePracticeDraftData = {
    body: VersionWrite;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/draft';
};

export type practiceSavePracticeDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceSavePracticeDraftError = practiceSavePracticeDraftErrors[keyof practiceSavePracticeDraftErrors];

export type practiceSavePracticeDraftResponses = {
    /**
     * Successful Response
     */
    200: VersionReceipt;
};

export type practiceSavePracticeDraftResponse = practiceSavePracticeDraftResponses[keyof practiceSavePracticeDraftResponses];

export type practiceReadPracticeVersionsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/draft/versions';
};

export type practiceReadPracticeVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceReadPracticeVersionsError = practiceReadPracticeVersionsErrors[keyof practiceReadPracticeVersionsErrors];

export type practiceReadPracticeVersionsResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type practiceReadPracticeVersionsResponse = practiceReadPracticeVersionsResponses[keyof practiceReadPracticeVersionsResponses];

export type practiceChoosePracticeDraftData = {
    body: VersionChoice;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/practice/draft/choose';
};

export type practiceChoosePracticeDraftErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type practiceChoosePracticeDraftError = practiceChoosePracticeDraftErrors[keyof practiceChoosePracticeDraftErrors];

export type practiceChoosePracticeDraftResponses = {
    /**
     * Successful Response
     */
    200: CollectionView;
};

export type practiceChoosePracticeDraftResponse = practiceChoosePracticeDraftResponses[keyof practiceChoosePracticeDraftResponses];

export type independentStartCheckData = {
    body: CheckStart;
    path: {
        /**
         * Origin Id
         */
        origin_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{origin_id}/independent';
};

export type independentStartCheckErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type independentStartCheckError = independentStartCheckErrors[keyof independentStartCheckErrors];

export type independentStartCheckResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type independentStartCheckResponse = independentStartCheckResponses[keyof independentStartCheckResponses];

export type independentConvertPracticeData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/practice';
};

export type independentConvertPracticeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type independentConvertPracticeError = independentConvertPracticeErrors[keyof independentConvertPracticeErrors];

export type independentConvertPracticeResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type independentConvertPracticeResponse = independentConvertPracticeResponses[keyof independentConvertPracticeResponses];

export type independentRetryCheckData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/independent/retry';
};

export type independentRetryCheckErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type independentRetryCheckError = independentRetryCheckErrors[keyof independentRetryCheckErrors];

export type independentRetryCheckResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type independentRetryCheckResponse = independentRetryCheckResponses[keyof independentRetryCheckResponses];

export type bossBossAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/boss/access';
};

export type bossBossAccessResponses = {
    /**
     * Successful Response
     */
    200: BossAccess;
};

export type bossBossAccessResponse = bossBossAccessResponses[keyof bossBossAccessResponses];

export type bossStartBossData = {
    body: BossStart;
    path?: never;
    query?: never;
    url: '/api/v1/boss/start';
};

export type bossStartBossErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bossStartBossError = bossStartBossErrors[keyof bossStartBossErrors];

export type bossStartBossResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type bossStartBossResponse = bossStartBossResponses[keyof bossStartBossResponses];

export type bossReadBossData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/boss/tasks/{run_id}';
};

export type bossReadBossErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bossReadBossError = bossReadBossErrors[keyof bossReadBossErrors];

export type bossReadBossResponses = {
    /**
     * Successful Response
     */
    200: BossPublic;
};

export type bossReadBossResponse = bossReadBossResponses[keyof bossReadBossResponses];

export type topicsListTopicsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/topics';
};

export type topicsListTopicsResponses = {
    /**
     * Response Topics-List Topics
     *
     * Successful Response
     */
    200: Array<TopicPublic>;
};

export type topicsListTopicsResponse = topicsListTopicsResponses[keyof topicsListTopicsResponses];

export type topicsReadTopicData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}';
};

export type topicsReadTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsReadTopicError = topicsReadTopicErrors[keyof topicsReadTopicErrors];

export type topicsReadTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsReadTopicResponse = topicsReadTopicResponses[keyof topicsReadTopicResponses];

export type topicsRequestAnalysisData = {
    body: AnalyzeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/topics/analyze';
};

export type topicsRequestAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsRequestAnalysisError = topicsRequestAnalysisErrors[keyof topicsRequestAnalysisErrors];

export type topicsRequestAnalysisResponses = {
    /**
     * Successful Response
     */
    202: TopicPublic;
};

export type topicsRequestAnalysisResponse = topicsRequestAnalysisResponses[keyof topicsRequestAnalysisResponses];

export type topicsEditTopicData = {
    body: EditRequest;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}/edit';
};

export type topicsEditTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsEditTopicError = topicsEditTopicErrors[keyof topicsEditTopicErrors];

export type topicsEditTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsEditTopicResponse = topicsEditTopicResponses[keyof topicsEditTopicResponses];

export type topicsConfirmTopicData = {
    body: VersionRequest;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}/confirm';
};

export type topicsConfirmTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsConfirmTopicError = topicsConfirmTopicErrors[keyof topicsConfirmTopicErrors];

export type topicsConfirmTopicResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsConfirmTopicResponse = topicsConfirmTopicResponses[keyof topicsConfirmTopicResponses];

export type topicsStartTopicData = {
    body: StartRequest;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}/start';
};

export type topicsStartTopicErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsStartTopicError = topicsStartTopicErrors[keyof topicsStartTopicErrors];

export type topicsStartTopicResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type topicsStartTopicResponse = topicsStartTopicResponses[keyof topicsStartTopicResponses];

export type topicsJobActionData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
        /**
         * Job Id
         */
        job_id: string;
        /**
         * Action
         */
        action: 'stop' | 'retry';
    };
    query?: never;
    url: '/api/v1/topics/{topic_id}/jobs/{job_id}/{action}';
};

export type topicsJobActionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type topicsJobActionError = topicsJobActionErrors[keyof topicsJobActionErrors];

export type topicsJobActionResponses = {
    /**
     * Successful Response
     */
    200: TopicPublic;
};

export type topicsJobActionResponse = topicsJobActionResponses[keyof topicsJobActionResponses];

export type reviewsReadReviewData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/review';
};

export type reviewsReadReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsReadReviewError = reviewsReadReviewErrors[keyof reviewsReadReviewErrors];

export type reviewsReadReviewResponses = {
    /**
     * Response Reviews-Read Review
     *
     * Successful Response
     */
    200: ReviewPublic | null;
};

export type reviewsReadReviewResponse = reviewsReadReviewResponses[keyof reviewsReadReviewResponses];

export type reviewsStartReviewData = {
    body: ReviewStart;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/review';
};

export type reviewsStartReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsStartReviewError = reviewsStartReviewErrors[keyof reviewsStartReviewErrors];

export type reviewsStartReviewResponses = {
    /**
     * Successful Response
     */
    202: ReviewPublic;
};

export type reviewsStartReviewResponse = reviewsStartReviewResponses[keyof reviewsStartReviewResponses];

export type reviewsRetryReviewData = {
    body: ReviewResume;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/review/retry';
};

export type reviewsRetryReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsRetryReviewError = reviewsRetryReviewErrors[keyof reviewsRetryReviewErrors];

export type reviewsRetryReviewResponses = {
    /**
     * Successful Response
     */
    202: ReviewPublic;
};

export type reviewsRetryReviewResponse = reviewsRetryReviewResponses[keyof reviewsRetryReviewResponses];

export type reviewsStopReviewData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/review/stop';
};

export type reviewsStopReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type reviewsStopReviewError = reviewsStopReviewErrors[keyof reviewsStopReviewErrors];

export type reviewsStopReviewResponses = {
    /**
     * Successful Response
     */
    200: ReviewPublic;
};

export type reviewsStopReviewResponse = reviewsStopReviewResponses[keyof reviewsStopReviewResponses];

export type jdsListJdsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jds';
};

export type jdsListJdsResponses = {
    /**
     * Response Jds-List Jds
     *
     * Successful Response
     */
    200: Array<JDPublic>;
};

export type jdsListJdsResponse = jdsListJdsResponses[keyof jdsListJdsResponses];

export type jdsReadJdData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/jds/{topic_id}';
};

export type jdsReadJdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jdsReadJdError = jdsReadJdErrors[keyof jdsReadJdErrors];

export type jdsReadJdResponses = {
    /**
     * Successful Response
     */
    200: JDPublic;
};

export type jdsReadJdResponse = jdsReadJdResponses[keyof jdsReadJdResponses];

export type jdsAnalyzeJdData = {
    body: AnalyzeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/jds/analyze';
};

export type jdsAnalyzeJdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jdsAnalyzeJdError = jdsAnalyzeJdErrors[keyof jdsAnalyzeJdErrors];

export type jdsAnalyzeJdResponses = {
    /**
     * Successful Response
     */
    202: JDPublic;
};

export type jdsAnalyzeJdResponse = jdsAnalyzeJdResponses[keyof jdsAnalyzeJdResponses];

export type jdsSelectRoleData = {
    body: SelectRequest;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/api/v1/jds/{topic_id}/select';
};

export type jdsSelectRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jdsSelectRoleError = jdsSelectRoleErrors[keyof jdsSelectRoleErrors];

export type jdsSelectRoleResponses = {
    /**
     * Successful Response
     */
    200: JDPublic;
};

export type jdsSelectRoleResponse = jdsSelectRoleResponses[keyof jdsSelectRoleResponses];

export type healthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type healthHealthResponses = {
    /**
     * Response Health-Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthHealthResponse = healthHealthResponses[keyof healthHealthResponses];
