// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Answer
 */
export type Answer = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Value
     */
    value: number | Array<number> | string;
    /**
     * Reason
     */
    reason: string;
};

/**
 * AnswerQuote
 */
export type AnswerQuote = {
    /**
     * Input
     */
    input: 'original' | 'clarification';
    /**
     * Field
     */
    field: 'value' | 'reason';
    /**
     * Quote
     */
    quote: string;
};

/**
 * Attempt
 */
export type Attempt = {
    /**
     * Number
     */
    number: number;
    /**
     * Code
     */
    code: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens?: number | null;
    /**
     * Completion Tokens
     */
    completion_tokens?: number | null;
    /**
     * Total Tokens
     */
    total_tokens?: number | null;
};

/**
 * Background
 */
export type Background = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Boundary
     */
    boundary: string;
};

/**
 * Body_accounts-login
 */
export type Body_accounts_login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Capability
 */
export type Capability = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Criterion
     */
    criterion: string;
    /**
     * Background Id
     */
    background_id: string;
    /**
     * Levels
     */
    levels: Array<Level>;
};

/**
 * Catalog
 */
export type Catalog = {
    /**
     * Version
     */
    version: string;
    /**
     * Quality
     */
    quality: string;
    /**
     * Difficulty Criteria
     */
    difficulty_criteria: {
        [key: string]: string;
    };
    /**
     * Backgrounds
     */
    backgrounds: Array<Background>;
    /**
     * Domains
     */
    domains: [
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain,
        Domain
    ];
};

/**
 * Citation
 */
export type Citation = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Quote
     */
    quote: string;
};

/**
 * Clarify
 */
export type Clarify = {
    /**
     * Answers
     */
    answers?: Array<Answer> | null;
};

/**
 * ConceptContent
 */
export type ConceptContent = {
    /**
     * Plain
     */
    plain: string;
    /**
     * Example
     */
    example: string;
    /**
     * Relation
     */
    relation: string;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
    /**
     * Principle
     */
    principle?: string | null;
};

/**
 * Domain
 */
export type Domain = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Capabilities
     */
    capabilities: Array<Capability>;
    /**
     * Examples
     */
    examples: Array<Example>;
};

/**
 * EvaluationInputs
 */
export type EvaluationInputs = {
    original: InputSnapshot;
    clarification?: InputSnapshot | null;
    /**
     * Clarification Used
     */
    clarification_used: boolean;
};

/**
 * EvaluationPublic
 */
export type EvaluationPublic = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Frozen Sequence
     */
    frozen_sequence: number | null;
    /**
     * Frozen At
     */
    frozen_at: string | null;
    inputs: EvaluationInputs;
    result: GradingCandidate | null;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Can Retry
     */
    can_retry: boolean;
};

/**
 * EvaluationStart
 */
export type EvaluationStart = {
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
};

/**
 * EvidenceKey
 */
export type EvidenceKey = {
    /**
     * Capability Id
     */
    capability_id: string;
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Background Id
     */
    background_id: string;
};

/**
 * Example
 */
export type Example = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Capability Ids
     */
    capability_ids: Array<string>;
    /**
     * Task
     */
    task: string;
    /**
     * Acceptable
     */
    acceptable: string;
    /**
     * Insufficient
     */
    insufficient: string;
};

/**
 * FileEntry
 */
export type FileEntry = {
    /**
     * Path
     */
    path: string;
    /**
     * Sha
     */
    sha: string;
    /**
     * Kind
     */
    kind: 'tree' | 'blob' | 'commit';
    /**
     * Mode
     */
    mode: string;
    /**
     * Size
     */
    size?: number;
};

/**
 * Finding
 */
export type Finding = {
    /**
     * Kind
     */
    kind: 'module' | 'entry' | 'call' | 'state' | 'storage';
    /**
     * Subject
     */
    subject: string;
    /**
     * Relation
     */
    relation: string;
    /**
     * Target
     */
    target: string;
    /**
     * Evidence
     */
    evidence: Array<Location>;
};

/**
 * Fragment
 */
export type Fragment = {
    /**
     * Path
     */
    path: string;
    /**
     * Blob
     */
    blob: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Total Lines
     */
    total_lines: number;
    /**
     * Text
     */
    text: string;
};

/**
 * GradingCandidate
 */
export type GradingCandidate = {
    /**
     * Items
     */
    items: Array<GradingItem>;
};

/**
 * GradingItem
 */
export type GradingItem = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Conclusion
     */
    conclusion: 'pass' | 'evidenced_fail' | 'unclear';
    /**
     * Answer Quotes
     */
    answer_quotes: Array<AnswerQuote>;
    /**
     * Grounding
     */
    grounding: Array<Grounding>;
    /**
     * Interpreted Value
     */
    interpreted_value: number | Array<number> | string | null;
    /**
     * Interpreted Reasoning
     */
    interpreted_reasoning: number | Array<number> | string | null;
    /**
     * Reason Claims
     */
    reason_claims: Array<ReasonClaim>;
    /**
     * Rule Quote
     */
    rule_quote: string | null;
    /**
     * Counterexample Quote
     */
    counterexample_quote: string | null;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Gap
     */
    gap: string | null;
};

/**
 * Grounding
 */
export type Grounding = {
    /**
     * Evidence Id
     */
    evidence_id: string;
    /**
     * Fact
     */
    fact: string;
    /**
     * Value
     */
    value: string;
    citation: Citation;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HelpAnswer
 */
export type HelpAnswer = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Value
     */
    value?: number | Array<number> | string | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * HelpCreate
 */
export type HelpCreate = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    input: HelpInput;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * HelpInput
 */
export type HelpInput = {
    /**
     * Question
     */
    question: string;
    /**
     * Depth
     */
    depth?: 'basic' | 'deep';
    /**
     * Answers
     */
    answers?: Array<HelpAnswer>;
};

/**
 * HelpPublic
 */
export type HelpPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    input: HelpInput;
    /**
     * Created Sequence
     */
    created_sequence: number;
    /**
     * Generated Sequence
     */
    generated_sequence: number | null;
    /**
     * Checked Sequence
     */
    checked_sequence: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Direction
     */
    direction: string | null;
    /**
     * Requires Independent Confirmation
     */
    requires_independent_confirmation: boolean;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Deliveries
     */
    deliveries: Array<PublicDelivery>;
    /**
     * Can Retry
     */
    can_retry: boolean;
};

/**
 * HelpPublication
 */
export type HelpPublication = {
    /**
     * Help Id
     */
    help_id: string;
    /**
     * Delivery Id
     */
    delivery_id: string;
    /**
     * Receipt Token
     */
    receipt_token: string;
    content: ConceptContent;
    /**
     * Content Hash
     */
    content_hash: string;
    /**
     * Exposure Sequence
     */
    exposure_sequence: number;
};

/**
 * InputSnapshot
 */
export type InputSnapshot = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Answers
     */
    answers: Array<Answer>;
};

/**
 * InvitationPublic
 */
export type InvitationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Status
     */
    status: 'unused' | 'used' | 'revoked';
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Judgment
 */
export type Judgment = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'choice' | 'order' | 'prediction';
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids: Array<string>;
};

/**
 * Level
 */
export type Level = {
    /**
     * Difficulty
     */
    difficulty: '基础' | '进阶' | '综合';
    /**
     * Required
     */
    required?: Array<EvidenceKey>;
    /**
     * Alternatives
     */
    alternatives?: Array<Array<EvidenceKey>>;
};

/**
 * Location
 */
export type Location = {
    /**
     * Path
     */
    path: string;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Quote
     */
    quote: string;
};

/**
 * ModelConfigPublic
 */
export type ModelConfigPublic = {
    /**
     * Version
     */
    version: string;
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Has Key
     */
    has_key?: boolean;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSave = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * PasswordResetEmail
 */
export type PasswordResetEmail = {
    /**
     * Email
     */
    email: string;
};

/**
 * PasswordResetRequest
 */
export type PasswordResetRequest = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ProbeInput
 */
export type ProbeInput = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id?: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * ProbeResult
 */
export type ProbeResult = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Models
     */
    models?: Array<string>;
    /**
     * Attempts
     */
    attempts?: Array<Attempt>;
};

/**
 * ProjectMap
 */
export type ProjectMap = {
    /**
     * Confirmed
     */
    confirmed?: Array<Finding>;
    /**
     * Unverified
     */
    unverified?: Array<Finding>;
    /**
     * Missing
     */
    missing?: Array<string>;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Reused From Id
     */
    reused_from_id: string | null;
    snapshot: Snapshot | null;
    project_map: ProjectMap | null;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
};

/**
 * ProjectStart
 */
export type ProjectStart = {
    /**
     * Url
     */
    url: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Reanalyze
     */
    reanalyze?: boolean;
};

/**
 * PublicCase
 */
export type PublicCase = {
    target: EvidenceKey;
    /**
     * Catalog Version
     */
    catalog_version: string;
    /**
     * Title
     */
    title: string;
    /**
     * Task
     */
    task: string;
    /**
     * Assumptions
     */
    assumptions: Array<string>;
    /**
     * Evidence
     */
    evidence: Array<PublicEvidence>;
    /**
     * Judgments
     */
    judgments: Array<Judgment>;
    /**
     * Sources
     */
    sources: Array<Source>;
    /**
     * Quality
     */
    quality?: string;
};

/**
 * PublicDelivery
 */
export type PublicDelivery = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Exposure Sequence
     */
    exposure_sequence: number;
    /**
     * Attempt Id
     */
    attempt_id: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Delivered Text
     */
    delivered_text: string;
    /**
     * Direction
     */
    direction: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Evidence
     */
    evidence: string;
};

/**
 * PublicEvidence
 */
export type PublicEvidence = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: '教学材料';
    /**
     * Text
     */
    text: string;
    /**
     * Citations
     */
    citations: Array<Citation>;
};

/**
 * ReasonClaim
 */
export type ReasonClaim = {
    /**
     * Answer Quote
     */
    answer_quote: number;
    /**
     * Grounding
     */
    grounding: number;
    /**
     * Interpreted Fact Value
     */
    interpreted_fact_value: string;
};

/**
 * RegistrationPublic
 */
export type RegistrationPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Verification Sent
     */
    verification_sent: boolean;
};

/**
 * RelevanceItem
 */
export type RelevanceItem = {
    /**
     * Judgment Id
     */
    judgment_id: string;
    /**
     * Status
     */
    status: 'related' | 'unrelated' | 'unclear';
};

/**
 * RenderingReceipt
 */
export type RenderingReceipt = {
    /**
     * Token
     */
    token: string;
};

/**
 * Repository
 */
export type Repository = {
    /**
     * Owner
     */
    owner: string;
    /**
     * Name
     */
    name: string;
    /**
     * Commit
     */
    commit: string;
    /**
     * Tree
     */
    tree: string;
    /**
     * Ref
     */
    ref: string;
    /**
     * Focus
     */
    focus?: string;
    /**
     * Start Line
     */
    start_line?: number;
    /**
     * End Line
     */
    end_line?: number | null;
};

/**
 * Snapshot
 */
export type Snapshot = {
    repository: Repository;
    /**
     * Entries
     */
    entries?: Array<FileEntry>;
    /**
     * Fragments
     */
    fragments?: Array<Fragment>;
    /**
     * Excluded
     */
    excluded?: {
        [key: string]: string;
    };
    /**
     * Directories
     */
    directories?: Array<FileEntry>;
    /**
     * Files
     */
    files?: Array<FileEntry>;
    /**
     * Offsets
     */
    offsets?: {
        [key: string]: number;
    };
    /**
     * Requests
     */
    requests?: number;
    /**
     * Bytes
     */
    bytes?: number;
    /**
     * Listing Complete
     */
    listing_complete?: boolean;
};

/**
 * Source
 */
export type Source = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Version
     */
    version: string;
    /**
     * Locator
     */
    locator: string;
    /**
     * Text
     */
    text: string;
};

/**
 * Start
 */
export type Start = {
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Previous Run Id
     */
    previous_run_id?: string | null;
};

/**
 * SubmissionPublic
 */
export type SubmissionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Original Id
     */
    original_id: string | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Answers
     */
    answers: Array<Answer>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Relevance
     */
    relevance: Array<RelevanceItem>;
    /**
     * Neutral Clarification
     */
    neutral_clarification: boolean;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    /**
     * Can Retry
     */
    can_retry: boolean;
};

/**
 * SubmissionState
 */
export type SubmissionState = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Submissions
     */
    submissions: Array<SubmissionPublic>;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Awarded Points
     */
    awarded_points: number;
    /**
     * Total Points
     */
    total_points: number;
    /**
     * Rule Version
     */
    rule_version: string | null;
};

/**
 * Submit
 */
export type Submit = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Expected Config Version
     */
    expected_config_version: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
    /**
     * Evaluate After Submit
     */
    evaluate_after_submit?: boolean;
    /**
     * Answers
     */
    answers: Array<Answer>;
    /**
     * Previous Submission Id
     */
    previous_submission_id?: string | null;
};

/**
 * TaskPublic
 */
export type TaskPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Config Version
     */
    config_version: string;
    /**
     * Destination
     */
    destination: string;
    /**
     * Model Id
     */
    model_id: string;
    target: EvidenceKey;
    /**
     * Goal
     */
    goal: string;
    /**
     * Attempts
     */
    attempts: Array<Attempt>;
    case: PublicCase | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Invitation Code
     */
    invitation_code: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerificationRequest
 */
export type VerificationRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * ModelConfigSave
 */
export type ModelConfigSaveWritable = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Expected Version
     */
    expected_version?: string | null;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

/**
 * ProbeInput
 */
export type ProbeInputWritable = {
    /**
     * Service Url
     */
    service_url: string;
    /**
     * Model Id
     */
    model_id?: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Disclosure Accepted
     */
    disclosure_accepted: boolean;
};

export type accountsLoginData = {
    body: Body_accounts_login;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type accountsLoginErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsLoginError = accountsLoginErrors[keyof accountsLoginErrors];

export type accountsLoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type accountsLoginResponse = accountsLoginResponses[keyof accountsLoginResponses];

export type accountsMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type accountsMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsMeResponse = accountsMeResponses[keyof accountsMeResponses];

export type accountsTrainingAccessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/access';
};

export type accountsTrainingAccessResponses = {
    /**
     * Response Accounts-Training Access
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type accountsTrainingAccessResponse = accountsTrainingAccessResponses[keyof accountsTrainingAccessResponses];

export type accountsRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type accountsRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRegisterError = accountsRegisterErrors[keyof accountsRegisterErrors];

export type accountsRegisterResponses = {
    /**
     * Successful Response
     */
    201: RegistrationPublic;
};

export type accountsRegisterResponse = accountsRegisterResponses[keyof accountsRegisterResponses];

export type accountsInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/invitations';
};

export type accountsInvitationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsInvitationsError = accountsInvitationsErrors[keyof accountsInvitationsErrors];

export type accountsInvitationsResponses = {
    /**
     * Response Accounts-Invitations
     *
     * Successful Response
     */
    200: Array<InvitationPublic>;
};

export type accountsInvitationsResponse = accountsInvitationsResponses[keyof accountsInvitationsResponses];

export type accountsGenerateInvitationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/invitations';
};

export type accountsGenerateInvitationResponses = {
    /**
     * Successful Response
     */
    201: InvitationPublic;
};

export type accountsGenerateInvitationResponse = accountsGenerateInvitationResponses[keyof accountsGenerateInvitationResponses];

export type accountsRevokeData = {
    body?: never;
    path: {
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/api/v1/invitations/{invitation_id}/revoke';
};

export type accountsRevokeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsRevokeError = accountsRevokeErrors[keyof accountsRevokeErrors];

export type accountsRevokeResponses = {
    /**
     * Successful Response
     */
    200: InvitationPublic;
};

export type accountsRevokeResponse = accountsRevokeResponses[keyof accountsRevokeResponses];

export type accountsLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/logout';
};

export type accountsLogoutResponses = {
    /**
     * Response Accounts-Logout
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsLogoutResponse = accountsLogoutResponses[keyof accountsLogoutResponses];

export type accountsResendVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verification-email';
};

export type accountsResendVerificationResponses = {
    /**
     * Response Accounts-Resend Verification
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResendVerificationResponse = accountsResendVerificationResponses[keyof accountsResendVerificationResponses];

export type accountsVerifyEmailData = {
    body: VerificationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/verify-email';
};

export type accountsVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsVerifyEmailError = accountsVerifyEmailErrors[keyof accountsVerifyEmailErrors];

export type accountsVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type accountsVerifyEmailResponse = accountsVerifyEmailResponses[keyof accountsVerifyEmailResponses];

export type accountsPasswordResetEmailData = {
    body: PasswordResetEmail;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/request';
};

export type accountsPasswordResetEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPasswordResetEmailError = accountsPasswordResetEmailErrors[keyof accountsPasswordResetEmailErrors];

export type accountsPasswordResetEmailResponses = {
    /**
     * Response Accounts-Password Reset Email
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type accountsPasswordResetEmailResponse = accountsPasswordResetEmailResponses[keyof accountsPasswordResetEmailResponses];

export type accountsResetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/v1/password-reset/confirm';
};

export type accountsResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsResetPasswordError = accountsResetPasswordErrors[keyof accountsResetPasswordErrors];

export type accountsResetPasswordResponses = {
    /**
     * Response Accounts-Reset Password
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type accountsResetPasswordResponse = accountsResetPasswordResponses[keyof accountsResetPasswordResponses];

export type capabilitiesReadCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/capabilities/catalog';
};

export type capabilitiesReadCatalogResponses = {
    /**
     * Successful Response
     */
    200: Catalog;
};

export type capabilitiesReadCatalogResponse = capabilitiesReadCatalogResponses[keyof capabilitiesReadCatalogResponses];

export type modelconfigDeleteConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Expected Version
         */
        expected_version: string;
    };
    url: '/api/v1/model-config';
};

export type modelconfigDeleteConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigDeleteConfigError = modelconfigDeleteConfigErrors[keyof modelconfigDeleteConfigErrors];

export type modelconfigDeleteConfigResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type modelconfigDeleteConfigResponse = modelconfigDeleteConfigResponses[keyof modelconfigDeleteConfigResponses];

export type modelconfigReadConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigReadConfigResponses = {
    /**
     * Response Modelconfig-Read Config
     *
     * Successful Response
     */
    200: ModelConfigPublic | null;
};

export type modelconfigReadConfigResponse = modelconfigReadConfigResponses[keyof modelconfigReadConfigResponses];

export type modelconfigSaveConfigData = {
    body: ModelConfigSaveWritable;
    path?: never;
    query?: never;
    url: '/api/v1/model-config';
};

export type modelconfigSaveConfigErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigSaveConfigError = modelconfigSaveConfigErrors[keyof modelconfigSaveConfigErrors];

export type modelconfigSaveConfigResponses = {
    /**
     * Successful Response
     */
    200: ModelConfigPublic;
};

export type modelconfigSaveConfigResponse = modelconfigSaveConfigResponses[keyof modelconfigSaveConfigResponses];

export type modelconfigProbeData = {
    body: ProbeInputWritable;
    path: {
        /**
         * Kind
         */
        kind: 'test' | 'models';
    };
    query?: never;
    url: '/api/v1/model-config/probe/{kind}';
};

export type modelconfigProbeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type modelconfigProbeError = modelconfigProbeErrors[keyof modelconfigProbeErrors];

export type modelconfigProbeResponses = {
    /**
     * Successful Response
     */
    200: ProbeResult;
};

export type modelconfigProbeResponse = modelconfigProbeResponses[keyof modelconfigProbeResponses];

export type trainingStartData = {
    body: Start;
    path?: never;
    query?: never;
    url: '/api/v1/training/random';
};

export type trainingStartErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingStartError = trainingStartErrors[keyof trainingStartErrors];

export type trainingStartResponses = {
    /**
     * Successful Response
     */
    202: TaskPublic;
};

export type trainingStartResponse = trainingStartResponses[keyof trainingStartResponses];

export type trainingLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/training/tasks';
};

export type trainingLatestResponses = {
    /**
     * Response Training-Latest
     *
     * Successful Response
     */
    200: Array<TaskPublic>;
};

export type trainingLatestResponse = trainingLatestResponses[keyof trainingLatestResponses];

export type trainingReadData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}';
};

export type trainingReadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingReadError = trainingReadErrors[keyof trainingReadErrors];

export type trainingReadResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type trainingReadResponse = trainingReadResponses[keyof trainingReadResponses];

export type trainingStopData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/stop';
};

export type trainingStopErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type trainingStopError = trainingStopErrors[keyof trainingStopErrors];

export type trainingStopResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type trainingStopResponse = trainingStopResponses[keyof trainingStopResponses];

export type submissionsReadSubmissionsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions';
};

export type submissionsReadSubmissionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsReadSubmissionsError = submissionsReadSubmissionsErrors[keyof submissionsReadSubmissionsErrors];

export type submissionsReadSubmissionsResponses = {
    /**
     * Successful Response
     */
    200: SubmissionState;
};

export type submissionsReadSubmissionsResponse = submissionsReadSubmissionsResponses[keyof submissionsReadSubmissionsResponses];

export type submissionsSubmitData = {
    body: Submit;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions';
};

export type submissionsSubmitErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsSubmitError = submissionsSubmitErrors[keyof submissionsSubmitErrors];

export type submissionsSubmitResponses = {
    /**
     * Successful Response
     */
    202: SubmissionState;
};

export type submissionsSubmitResponse = submissionsSubmitResponses[keyof submissionsSubmitResponses];

export type submissionsRetrySubmissionData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions/{submission_id}/retry';
};

export type submissionsRetrySubmissionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsRetrySubmissionError = submissionsRetrySubmissionErrors[keyof submissionsRetrySubmissionErrors];

export type submissionsRetrySubmissionResponses = {
    /**
     * Successful Response
     */
    202: SubmissionState;
};

export type submissionsRetrySubmissionResponse = submissionsRetrySubmissionResponses[keyof submissionsRetrySubmissionResponses];

export type submissionsStopSubmissionData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Submission Id
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/submissions/{submission_id}/stop';
};

export type submissionsStopSubmissionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type submissionsStopSubmissionError = submissionsStopSubmissionErrors[keyof submissionsStopSubmissionErrors];

export type submissionsStopSubmissionResponses = {
    /**
     * Successful Response
     */
    200: SubmissionState;
};

export type submissionsStopSubmissionResponse = submissionsStopSubmissionResponses[keyof submissionsStopSubmissionResponses];

export type projectsLatestProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type projectsLatestProjectsResponses = {
    /**
     * Response Projects-Latest Projects
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type projectsLatestProjectsResponse = projectsLatestProjectsResponses[keyof projectsLatestProjectsResponses];

export type projectsStartProjectData = {
    body: ProjectStart;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type projectsStartProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsStartProjectError = projectsStartProjectErrors[keyof projectsStartProjectErrors];

export type projectsStartProjectResponses = {
    /**
     * Successful Response
     */
    202: ProjectPublic;
};

export type projectsStartProjectResponse = projectsStartProjectResponses[keyof projectsStartProjectResponses];

export type projectsReadProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}';
};

export type projectsReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsReadProjectError = projectsReadProjectErrors[keyof projectsReadProjectErrors];

export type projectsReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsReadProjectResponse = projectsReadProjectResponses[keyof projectsReadProjectResponses];

export type projectsRetryProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}/retry';
};

export type projectsRetryProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsRetryProjectError = projectsRetryProjectErrors[keyof projectsRetryProjectErrors];

export type projectsRetryProjectResponses = {
    /**
     * Successful Response
     */
    202: ProjectPublic;
};

export type projectsRetryProjectResponse = projectsRetryProjectResponses[keyof projectsRetryProjectResponses];

export type projectsStopProjectData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{run_id}/stop';
};

export type projectsStopProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsStopProjectError = projectsStopProjectErrors[keyof projectsStopProjectErrors];

export type projectsStopProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsStopProjectResponse = projectsStopProjectResponses[keyof projectsStopProjectResponses];

export type evaluationsReadEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation';
};

export type evaluationsReadEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsReadEvaluationError = evaluationsReadEvaluationErrors[keyof evaluationsReadEvaluationErrors];

export type evaluationsReadEvaluationResponses = {
    /**
     * Response Evaluations-Read Evaluation
     *
     * Successful Response
     */
    200: EvaluationPublic | null;
};

export type evaluationsReadEvaluationResponse = evaluationsReadEvaluationResponses[keyof evaluationsReadEvaluationResponses];

export type evaluationsStartEvaluationData = {
    body: EvaluationStart;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation';
};

export type evaluationsStartEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsStartEvaluationError = evaluationsStartEvaluationErrors[keyof evaluationsStartEvaluationErrors];

export type evaluationsStartEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsStartEvaluationResponse = evaluationsStartEvaluationResponses[keyof evaluationsStartEvaluationResponses];

export type evaluationsClarifyEvaluationData = {
    body: Clarify;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/clarification';
};

export type evaluationsClarifyEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsClarifyEvaluationError = evaluationsClarifyEvaluationErrors[keyof evaluationsClarifyEvaluationErrors];

export type evaluationsClarifyEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsClarifyEvaluationResponse = evaluationsClarifyEvaluationResponses[keyof evaluationsClarifyEvaluationResponses];

export type evaluationsRetryEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/retry';
};

export type evaluationsRetryEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsRetryEvaluationError = evaluationsRetryEvaluationErrors[keyof evaluationsRetryEvaluationErrors];

export type evaluationsRetryEvaluationResponses = {
    /**
     * Successful Response
     */
    202: EvaluationPublic;
};

export type evaluationsRetryEvaluationResponse = evaluationsRetryEvaluationResponses[keyof evaluationsRetryEvaluationResponses];

export type evaluationsStopEvaluationData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/evaluation/stop';
};

export type evaluationsStopEvaluationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type evaluationsStopEvaluationError = evaluationsStopEvaluationErrors[keyof evaluationsStopEvaluationErrors];

export type evaluationsStopEvaluationResponses = {
    /**
     * Successful Response
     */
    200: EvaluationPublic;
};

export type evaluationsStopEvaluationResponse = evaluationsStopEvaluationResponses[keyof evaluationsStopEvaluationResponses];

export type conceptsListHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help';
};

export type conceptsListHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsListHelpError = conceptsListHelpErrors[keyof conceptsListHelpErrors];

export type conceptsListHelpResponses = {
    /**
     * Response Concepts-List Help
     *
     * Successful Response
     */
    200: Array<HelpPublic>;
};

export type conceptsListHelpResponse = conceptsListHelpResponses[keyof conceptsListHelpResponses];

export type conceptsRequestHelpData = {
    body: HelpCreate;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help';
};

export type conceptsRequestHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsRequestHelpError = conceptsRequestHelpErrors[keyof conceptsRequestHelpErrors];

export type conceptsRequestHelpResponses = {
    /**
     * Successful Response
     */
    202: HelpPublic;
};

export type conceptsRequestHelpResponse = conceptsRequestHelpResponses[keyof conceptsRequestHelpResponses];

export type conceptsRetryHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/retry';
};

export type conceptsRetryHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsRetryHelpError = conceptsRetryHelpErrors[keyof conceptsRetryHelpErrors];

export type conceptsRetryHelpResponses = {
    /**
     * Successful Response
     */
    202: HelpPublic;
};

export type conceptsRetryHelpResponse = conceptsRetryHelpResponses[keyof conceptsRetryHelpResponses];

export type conceptsStopHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/stop';
};

export type conceptsStopHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsStopHelpError = conceptsStopHelpErrors[keyof conceptsStopHelpErrors];

export type conceptsStopHelpResponses = {
    /**
     * Successful Response
     */
    200: HelpPublic;
};

export type conceptsStopHelpResponse = conceptsStopHelpResponses[keyof conceptsStopHelpResponses];

export type conceptsPublishHelpData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/deliver';
};

export type conceptsPublishHelpErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsPublishHelpError = conceptsPublishHelpErrors[keyof conceptsPublishHelpErrors];

export type conceptsPublishHelpResponses = {
    /**
     * Successful Response
     */
    200: HelpPublication;
};

export type conceptsPublishHelpResponse = conceptsPublishHelpResponses[keyof conceptsPublishHelpResponses];

export type conceptsConfirmRenderingData = {
    body: RenderingReceipt;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Help Id
         */
        help_id: string;
        /**
         * Delivery Id
         */
        delivery_id: string;
    };
    query?: never;
    url: '/api/v1/training/tasks/{run_id}/help/{help_id}/deliveries/{delivery_id}/receipt';
};

export type conceptsConfirmRenderingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conceptsConfirmRenderingError = conceptsConfirmRenderingErrors[keyof conceptsConfirmRenderingErrors];

export type conceptsConfirmRenderingResponses = {
    /**
     * Successful Response
     */
    200: HelpPublic;
};

export type conceptsConfirmRenderingResponse = conceptsConfirmRenderingResponses[keyof conceptsConfirmRenderingResponses];

export type healthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type healthHealthResponses = {
    /**
     * Response Health-Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type healthHealthResponse = healthHealthResponses[keyof healthHealthResponses];
