import { expect, test } from "@playwright/test"

test("关联补验失响应恢复、只解除原晋升、补验误判再挂回及删除Key后读取", async ({ page }) => {
  test.skip(!process.env.REVALIDATION_BROWSER_TOKEN, "由 boss_revalidation_browser.py 提供真实纠正记录和worker")
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto("/?boss=1")
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.REVALIDATION_BROWSER_TOKEN)
  await page.reload()
  const entry = page.getByRole("region", { name: "Boss挑战入口" })
  await expect(entry.getByRole("status")).toContainText("有1条晋升待补验")
  await expect(entry.getByText("服务器当前等级：初级程序员 · 累计修为：110", { exact: true })).toBeVisible()
  await entry.getByLabel("选择当前阶段或关联补验").selectOption(process.env.REVALIDATION_PROMOTION!)
  const launch = entry.getByRole("button", { name: "主动开始关联补验Boss（独立新案例）", exact: true })
  await expect(launch).toBeDisabled()
  await entry.getByRole("checkbox").check()
  let created = ""
  await page.route("**/api/v1/boss/start", async route => {
    const response = await route.fetch()
    expect(response.status()).toBe(202)
    created = (await response.json()).id
    await route.abort("failed")
  })
  await launch.focus(); await page.keyboard.press("Enter")
  await expect(entry.getByRole("alert")).toContainText("挑战发起未确认")
  await page.unroute("**/api/v1/boss/start")
  await entry.getByRole("button", { name: "重新读取Boss资格与配置" }).click()
  const stored = entry.locator(`a[href="/?training_run=${created}"]`)
  await expect(stored).toBeVisible(); await stored.click()
  const training = page.getByRole("region", { name: "随机第一关" })
  const result = page.getByRole("region", { name: "Boss结算与晋升" })
  await expect(training.getByText("保存失败的三个独立判断", { exact: true })).toBeVisible({ timeout: 15000 })
  await expect(training.getByLabel("草稿保存状态").getByRole("status")).not.toHaveText("正在读取已保存进度")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const fields = training.locator("fieldset").filter({ has: page.getByRole("textbox", { name: "这一判断的理由", exact: true }) })
  const reasons = training.getByRole("textbox", { name: "这一判断的理由", exact: true })
  await expect(reasons).toHaveCount(3)
  for (let i = 0; i < 3; i++) {
    await expect(reasons.nth(i)).toHaveValue("")
    const radio = fields.nth(i).getByRole("radio").first()
    await radio.focus(); await page.keyboard.press("Space")
    await reasons.nth(i).fill("依据本项冻结观察选择对应验证行动。")
  }
  await expect(training.getByLabel("草稿保存状态").getByRole("status")).toHaveText("草稿已保存")
  await page.reload()
  await expect(reasons.nth(2)).toHaveValue("依据本项冻结观察选择对应验证行动。")
  await training.getByText(/允许将当前公开题面与作答发送给此模型检查相关性/).click()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  await expect(result.getByText(/本轮补验通过事实已保存/)).toBeVisible({ timeout: 15000 })
  await expect(result.getByText(/本轮晋升已保存/)).toHaveCount(0)
  await expect(result.getByText("服务器当前等级：初级程序员 · 累计修为：120", { exact: true })).toBeVisible()
  await result.getByText("小白程序员 → 初级程序员：补验已通过", { exact: true }).click()
  await expect(result.getByText(/关联补验独立通过，仅解除这一条限制/)).toBeVisible()
  await result.screenshot({ path: "test-results/revalidation-320.png" })
  const review = page.getByRole("region", { name: "评分复核" })
  await review.getByLabel("确认评分复核目的地").check()
  await review.getByRole("button", { name: "申请一次评分复核" }).click()
  await expect(review.getByText("原判已更正，已按原作答位置回算当前完整历史", { exact: true })).toBeVisible({ timeout: 15000 })
  await result.getByRole("button", { name: "重新读取Boss结论" }).click()
  await expect(result.getByText("小白程序员 → 初级程序员：待补验", { exact: true })).toBeVisible()
  await expect(result.getByText(/记录3 · 终态复核确认/)).toBeVisible()
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await result.getByRole("button", { name: "重新读取Boss结论" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/revalidation-200.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "" })
  page.once("dialog", dialog => dialog.accept())
  await page.getByRole("button", { name: "删除配置及 Key", exact: true }).click()
  await expect(page.getByText("配置及 Key 已删除，旧版本不能发起新调用。", { exact: true })).toBeVisible()
  await result.getByRole("link", { name: "返回Boss入口，查看标准或主动新题重试" }).click()
  await expect(entry.getByRole("status")).toContainText("有1条晋升待补验")
  await expect(entry.getByText("请先保存可用模型配置后重读；既有挑战记录仍可查看。", { exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
