import { expect, test } from "@playwright/test"

test("6000阶段展示复合必考观察、真实晋升AI级且保留最高综合挑战", async ({ page, request }) => {
  test.skip(!process.env.BOSS_STAGES_BROWSER_TOKEN, "由 boss_stages_browser.py 提供受控账号与真实worker")
  const token = process.env.BOSS_STAGES_BROWSER_TOKEN!
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 320, height: 760 })
  await page.goto("/?boss=1")
  await page.evaluate(t => sessionStorage.setItem("token", t), token)
  await page.reload()
  const entry = page.getByRole("region", { name: "Boss挑战入口" })
  await expect(entry.getByText("服务器当前等级：传奇程序员 · 累计修为：6000", { exact: true })).toBeVisible()
  for (const id of ["diagnosis", "risk", "verification", "rollback"]) await expect(entry.getByText(new RegExp(`必考判断 ${id}`))).toBeVisible()
  for (const domain of ["performance.bottleneck", "data.query", "async.jobs"]) await expect(entry.getByText(new RegExp(`来源领域：${domain}`))).toBeVisible()
  await entry.screenshot({ path: "test-results/boss-stages-standard-320.png" })
  const launch = entry.getByRole("button", { name: "主动开始当前阶段Boss（独立新案例）", exact: true })
  await expect(launch).toBeDisabled()
  await entry.getByRole("checkbox").check()
  await launch.focus(); await page.keyboard.press("Enter")
  await expect(page).toHaveURL(/training_run=/)
  const identity = new URL(page.url()).searchParams.get("training_run")!
  const training = page.getByRole("region", { name: "随机第一关" })
  await expect(training.getByText("根据当前冻结情境完成各必考判断及相关理由", { exact: true })).toBeVisible({ timeout: 20000 })
  await expect(training.getByLabel("草稿保存状态").getByRole("status")).not.toHaveText("正在读取已保存进度")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const reasons = training.getByRole("textbox", { name: "这一判断的理由", exact: true })
  const fieldsets = training.locator("fieldset").filter({ has: page.getByRole("textbox", { name: "这一判断的理由", exact: true }) })
  await expect(reasons).toHaveCount(4)
  for (let i = 0; i < 4; i++) {
    const radio = fieldsets.nth(i).getByRole("radio").first()
    await expect(radio).toBeEnabled(); await radio.focus(); await page.keyboard.press("Space"); await expect(radio).toBeChecked()
    await reasons.nth(i).fill("依据本项全部观察，核对风险、因果与验证或回退条件。")
  }
  await expect(training.getByLabel("草稿保存状态").getByRole("status")).toHaveText("草稿已保存")
  await page.reload()
  await expect(reasons.nth(3)).toHaveValue("依据本项全部观察，核对风险、因果与验证或回退条件。")
  await training.getByText(/允许将当前公开题面与作答发送给此模型检查相关性/).click()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  const result = page.getByRole("region", { name: "Boss结算与晋升" })
  await expect(result.getByText(/本轮晋升已保存：传奇程序员 → AI级程序员/)).toBeVisible({ timeout: 20000 })
  await expect(page.getByText(/@.* · AI级程序员/)).toBeVisible()
  await expect(result.getByText("全部必考判断与必要观察均获得有效独立通过", { exact: true })).toBeVisible()
  await result.screenshot({ path: "test-results/boss-stages-ai-320.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await result.getByRole("button", { name: "重新读取Boss结论" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await result.screenshot({ path: "test-results/boss-stages-ai-200.png" })
  await page.reload()
  await expect(result.getByText(/本轮晋升已保存：传奇程序员 → AI级程序员/)).toBeVisible()
  await result.getByRole("link", { name: "返回Boss入口，查看标准或主动新题重试", exact: true }).click()
  await expect(entry.getByText(/保持最高等级，继续综合挑战/)).toBeVisible()
  await expect(entry.getByText(/boss-6000-v1-challenge/)).toBeVisible()
  const persisted = await (await request.get(`/api/v1/boss/tasks/${identity}`, { headers: { Authorization: `Bearer ${token}` } })).json()
  expect(persisted.current_level).toBe("AI级程序员")
  expect(persisted.points).toBe(6010)
  expect(persisted.promotion_id).toBeTruthy()
  expect(errors).toEqual([])
})
