import { expect, test } from "@playwright/test"

test("能力地图显示同键恢复证据并保留读取失败前的状态", async ({ page }) => {
  test.skip(!process.env.CAPABILITY_BROWSER_TOKEN, "受控五轮真实独立检验")
  await page.addInitScript(token => sessionStorage.setItem("token", token!), process.env.CAPABILITY_BROWSER_TOKEN)
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto("/")
  const map = page.getByRole("region", { name: "全栈能力与前置地图" })
  const proof = map.locator("details").filter({ has: page.getByText(`稳定 ID：${process.env.CAPABILITY_BROWSER_ID}`, { exact: true }) }).first()
  await expect(proof.locator("summary").first()).toContainText("已验证")
  await proof.locator("summary").first().focus()
  await page.keyboard.press("Enter")
  await expect(proof.getByText(/当前连续独立通过：2/)).toBeVisible()
  await proof.getByText("查看状态依据（5 条原答）", { exact: true }).click()
  await expect(proof.getByText(/结果：有据失败/)).toBeVisible()
  await expect(proof.getByRole("link", { name: "查看原轮与记录" })).toHaveCount(5)
  await proof.getByText(/结果：有据失败/).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/capability-evidence-320.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await proof.getByText(/结果：有据失败/).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/capability-evidence-200.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "" })
  await map.getByRole("radio", { name: "进阶", exact: true }).check()
  await expect(proof.locator("summary").first()).toContainText("未验证")
  await map.getByRole("radio", { name: "基础", exact: true }).check()
  await expect(proof.locator("summary").first()).toContainText("已验证")
  await page.route("**/capabilities/evidence", route => route.fulfill({ status: 503, json: { detail: "controlled outage" } }))
  await map.getByRole("button", { name: "重新读取能力目录" }).click()
  await expect(map.getByText(/能力证据读取失败/)).toBeVisible()
  await expect(proof.locator("summary").first()).toContainText("已验证")
  await page.unroute("**/capabilities/evidence")
  await map.getByRole("button", { name: "重新读取能力目录" }).click()
  await expect(map.getByText(/能力证据读取失败/)).toHaveCount(0)
  const headers = { Authorization: `Bearer ${process.env.CAPABILITY_BROWSER_TOKEN}` }
  const config = await (await page.request.get("/api/v1/model-config", { headers })).json()
  expect((await page.request.delete(`/api/v1/model-config?expected_version=${config.version}`, { headers })).status()).toBe(204)
  await page.reload()
  await expect(proof.locator("summary").first()).toContainText("已验证")
})
