import { expect, test } from "@playwright/test"

test("保存配置取消旧教练并展示真实部分用量", async ({ page }) => {
  test.skip(!process.env.CONFIG_SWITCH_TOKEN, "由 config_switch_browser.py 提供受控任务")
  await page.setViewportSize({ width: 320, height: 780 })
  await page.addInitScript(token => sessionStorage.setItem("token", token!), process.env.CONFIG_SWITCH_TOKEN)
  await page.goto(`/?training_run=${process.env.CONFIG_SWITCH_RUN}`)
  const config = page.getByRole("region", { name: "个人模型配置" })
  await expect(config.getByText(/将结束旧配置关联任务的后续调用/)).toBeVisible()
  await config.getByLabel("模型 ID", { exact: true }).fill("new-user-chosen-model")
  await config.getByRole("checkbox").check()
  await config.getByRole("button", { name: "保存配置", exact: true }).click()
  await expect(config.getByText("配置已保存。未调用模型服务，连接和教学质量尚未验证。")).toBeVisible()
  await config.getByRole("button", { name: "读取逐次与汇总用量" }).click()
  const usage = config.getByLabel("模型用量")
  await expect(usage.getByText(/另有 1 次未知，不能视为完整合计/)).toBeVisible()
  await expect(usage.getByText(/已记录 2 次尝试/)).toBeVisible()
  await usage.getByText("逐调用归属与真实用量").click()
  await expect(usage.getByText(/cancelled/)).toBeVisible()
  await expect(usage.getByText(/实际费用请查看模型服务商账单/)).toBeVisible()
  await usage.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/config-switch-320.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await config.getByRole("button", { name: "读取逐次与汇总用量" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/config-switch-200.png" })
  await page.reload()
  await expect(config.getByLabel("模型 ID", { exact: true })).toHaveValue("new-user-chosen-model")
  await expect(page.getByText("比较请求证据", { exact: true })).toBeVisible()
})

test("撤销与保存之间中断明确提示且只能主动恢复", async ({ page }) => {
  test.skip(!process.env.CONFIG_RECOVERY_TOKEN, "由 config_switch_browser.py 提供持久撤销状态")
  await page.addInitScript(token => sessionStorage.setItem("token", token!), process.env.CONFIG_RECOVERY_TOKEN)
  await page.goto("/")
  const config = page.getByRole("region", { name: "个人模型配置" })
  await expect(config.getByRole("alert")).toContainText("旧配置已撤销，不可再调用")
  await config.getByRole("checkbox").check()
  await config.getByRole("button", { name: "保存配置", exact: true }).click()
  await expect(config.getByText("配置已保存。未调用模型服务，连接和教学质量尚未验证。")).toBeVisible()
  await expect(config.getByRole("alert")).toHaveCount(0)
  await config.getByRole("button", { name: "读取逐次与汇总用量" }).click()
  await expect(config.getByText(/已记录 0 次尝试/)).toBeVisible()
})
