import { expect, test } from "@playwright/test"

test("主动提示示范、单项跟练草稿恢复与同轮奖励", async ({ page }) => {
  test.skip(!process.env.GUIDED_BROWSER_TOKEN, "由 guided_browser.py 提供真实任务")
  const errors: string[] = []
  page.on("pageerror", e => errors.push(e.message))
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto(`/?training_run=${process.env.GUIDED_BROWSER_RUN}`)
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.GUIDED_BROWSER_TOKEN)
  await page.reload()
  const training = page.getByRole("region", { name: "随机第一关" })
  await training.getByRole("button", { name: "概念", exact: true }).click()
  const coach = page.getByRole("region", { name: "概念教练" })
  await expect(coach.getByText("可接受结论：", { exact: true })).toHaveCount(0)
  await coach.getByRole("checkbox").check()
  await coach.getByRole("button", { name: "证据提示", exact: true }).click()
  await coach.getByRole("button", { name: "查看证据提示" }).click()
  await expect(coach.getByText("可接受结论：", { exact: true })).toHaveCount(0)
  await coach.getByRole("button", { name: "准备完整示范" }).click()
  await coach.getByRole("button", { name: "查看完整示范", exact: true }).click()
  await expect(coach.getByText("可接受结论：", { exact: true }).first()).toBeVisible()
  await coach.getByRole("button", { name: "自己做一个小练习" }).click()
  const practice = page.getByRole("region", { name: "示范后小练习" })
  await expect(practice.getByText("尚无已保存跟练草稿", { exact: true })).toBeVisible()
  await expect(practice.getByRole("radio").first()).not.toBeChecked()
  const reason = practice.getByLabel("我的跟练理由", { exact: true })
  await reason.fill("先核对处理记录，我还不知道是否执行过。")
  await expect(practice.getByText("跟练草稿已保存", { exact: true })).toBeVisible()
  await page.reload()
  await expect(coach.getByRole("button", { name: "自己做一个小练习" })).toBeVisible()
  await coach.getByRole("button", { name: "自己做一个小练习" }).click()
  await expect(reason).toHaveValue("先核对处理记录，我还不知道是否执行过。")
  await practice.getByRole("radio").nth(1).check()
  await reason.focus()
  await page.keyboard.press("Tab")
  await expect(practice.getByRole("checkbox")).toBeFocused()
  await page.keyboard.press("Space")
  await practice.getByRole("button", { name: "提交我的小练习" }).click()
  await expect(practice.getByText(/小练习已完成；同轮合计/)).toBeVisible()
  await expect(practice.getByText(/本轮修为：10 点/)).toBeVisible()
  await reason.scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/guided-320.png" })
  await reason.fill("复盘时仍要区分没有确认和没有执行。")
  await practice.getByRole("button", { name: "保存跟练复盘（不重评）" }).click()
  await expect(practice.getByText("跟练复盘已保存；未重评、未新增奖励，原题记录保留。", { exact: true })).toBeVisible()
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await practice.getByText(/本轮修为：10 点/).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/guided-200.png" })
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await expect(page.getByRole("button", { name: "正式交卷", exact: true })).toBeVisible()
  await expect(page.getByLabel("这一判断的理由", { exact: true }).first()).toHaveValue("")
  expect(errors).toEqual([])
})
