import { expect, test } from "@playwright/test"

test("主动陌生检验、原草稿隔离与冻结后提示确认", async ({ page }) => {
  test.skip(!process.env.INDEPENDENT_BROWSER_TOKEN, "由 independent_browser.py 提供真实任务")
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  const origin = process.env.INDEPENDENT_BROWSER_ORIGIN!
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto(`/?training_run=${origin}`)
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.INDEPENDENT_BROWSER_TOKEN)
  await page.reload()
  const training = page.getByRole("region", { name: "随机第一关" })
  const saved = training.getByLabel("草稿保存状态").getByRole("status")
  await expect(saved).toHaveText("尚无已保存草稿")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const reason = training.getByLabel("这一判断的理由", { exact: true }).first()
  await reason.fill("原轮草稿保留，不搬到独立检验。")
  await expect(saved).toHaveText("草稿已保存")
  await training.getByRole("checkbox", { name: /允许发送必要的新旧情境/ }).check()
  const newRun = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/independent"))
  await training.getByRole("button", { name: "检验自己：主动新建陌生案例" }).focus()
  await page.keyboard.press("Enter")
  const created = await (await newRun).json()
  expect(created.id).not.toBe(origin)
  expect(created.case).toBeNull()
  await expect(training.getByRole("status").filter({ hasText: "主动检验案例已就绪" })).toBeVisible({ timeout: 15000 })
  await expect(saved).toHaveText("尚无已保存草稿")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await expect(reason).toHaveValue("")
  const decision = training.getByRole("radio").first()
  await expect(decision).toBeEnabled()
  await decision.focus()
  await page.keyboard.press("Space")
  await expect(decision).toBeChecked()
  await reason.fill("提交成功已确认，应保留已有结果，避免重新执行。")
  await training.getByRole("checkbox", { name: /允许将当前公开题面与作答/ }).check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  const feedback = page.getByRole("region", { name: "本次反馈" })
  await expect(feedback.getByText(/符合独立通过条件的证据候选/)).toBeVisible({ timeout: 15000 })
  await feedback.screenshot({ path: "test-results/independent-pass-320.png" })
  await expect(saved).toHaveText("草稿已保存")
  await training.getByRole("button", { name: "概念", exact: true }).click()
  const coach = page.getByRole("region", { name: "概念教练" })
  await coach.getByRole("checkbox", { name: /允许/ }).check()
  await coach.getByRole("button", { name: "证据提示", exact: true }).click()
  const show = coach.getByRole("button", { name: "查看证据提示" })
  await expect(show).toBeVisible({ timeout: 15000 })
  await expect(show).toBeDisabled()
  const consent = coach.getByRole("checkbox", { name: /继续后本题转为练习/ })
  await expect(consent).toBeVisible()
  await expect(coach.getByText("可接受结论：", { exact: true })).toHaveCount(0)
  await coach.screenshot({ path: "test-results/independent-confirm-320.png" })
  await consent.focus()
  await page.keyboard.press("Space")
  const receipt = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/receipt"))
  await show.click()
  expect((await receipt).status()).toBe(200)
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await feedback.getByRole("button", { name: "重新读取评分" }).click()
  await expect(feedback.getByText(/符合独立通过条件的证据候选/)).toBeVisible()
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await feedback.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/independent-pass-200.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "" })
  await expect(saved).toHaveText("草稿已保存")
  await page.goto(`/?training_run=${origin}`)
  await expect(saved).toHaveText("草稿已保存")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await expect(reason).toHaveValue("原轮草稿保留，不搬到独立检验。")
  expect(errors).toEqual([])
})
