import { expect, test } from "@playwright/test"
const text = "后端工程师：处理请求重试。另有前端岗位。联系邮箱仅留在原文。"

test("JD 真实原文映射、重点确认、模拟作答反馈与恢复", async ({ page }) => {
  test.skip(!process.env.JD_BROWSER_TOKEN, "由 jd_browser.py 提供真实受控服务")
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message))
  let starts = 0; page.on("request", r => { if (r.method() === "POST" && /\/topics\/[^/]+\/start$/.test(r.url())) starts++ })
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.JD_BROWSER_TOKEN); await page.reload()
  const region = page.getByRole("region", { name: "JD 定向路线", exact: true })
  await region.getByRole("button", { name: "输入 JD 或恢复路线" }).click()
  await region.getByLabel("招聘原文", { exact: true }).fill(text)
  await region.getByLabel("允许发送本次 JD").check()
  await region.getByRole("button", { name: "分析 JD（先展示要求，不开题）" }).click()
  await expect(region.getByRole("button", { name: "选择岗位：后端工程师" })).toBeVisible({ timeout: 15000 })
  await expect(region.getByText("尚未验证，不表示不会", { exact: true })).toBeVisible()
  await expect(region.getByText(/推断：从重试要求/)).toBeVisible()
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toHaveCount(0)
  await region.getByRole("button", { name: "选择岗位：后端工程师" }).click()
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeDisabled()
  await region.getByLabel("JD 训练重点").fill("比较确认丢失与执行证据，不把超时等同未执行")
  await expect(region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" })).toBeDisabled()
  const saved = page.waitForResponse(r => r.url().includes("/topics/") && r.url().endsWith("/edit") && r.status() === 200)
  await region.getByRole("button", { name: "保存 JD 训练重点为新版本" }).click(); await saved
  await expect(region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" })).toBeEnabled()
  await region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" }).focus(); await page.keyboard.press("Enter")
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeEnabled()
  await region.getByLabel("JD 训练重点").fill("先查处理日志与持久结果，再判断重试是否安全")
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeDisabled()
  await expect(region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" })).toBeDisabled()
  await region.getByRole("button", { name: "开始此 JD 教学模拟" }).evaluate((button: HTMLButtonElement) => button.click())
  expect(starts).toBe(0)
  await region.getByLabel("JD 训练难度").selectOption("进阶")
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeDisabled()
  await region.getByLabel("JD 训练难度").selectOption("基础")
  await region.getByRole("button", { name: "保存 JD 训练重点为新版本" }).click()
  await expect(region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" })).toBeEnabled()
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeDisabled()
  await region.getByRole("button", { name: "确认当前 JD 路线（不生成题目）" }).click()
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toBeEnabled()
  await region.screenshot({ path: "test-results/jd-route-320.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "200%")
  await region.getByRole("button", { name: "开始此 JD 教学模拟" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/jd-route-200.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "")
  await region.getByRole("button", { name: "开始此 JD 教学模拟" }).click()
  await expect(page).toHaveURL(/training_run=/)
  const training = page.getByRole("region", { name: "随机第一关" })
  await expect(training.getByRole("complementary", { name: "JD 教学模拟来源" })).toContainText("不是该公司的真实架构")
  await expect(training.getByText("尚无已保存草稿", { exact: true })).toBeVisible({ timeout: 15000 })
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await training.getByRole("radio").first().check()
  await training.getByLabel("这一判断的理由", { exact: true }).fill("确认可能丢失，应查服务端执行证据再决定重试。")
  await expect(training.getByText("草稿已保存", { exact: true })).toBeVisible()
  await training.getByRole("checkbox").filter({ visible: true }).last().check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  await expect(training.getByText("通过", { exact: true })).toBeVisible({ timeout: 15000 })
  await page.reload()
  await expect(region.getByLabel("JD 训练重点")).toHaveValue("先查处理日志与持久结果，再判断重试是否安全")
  await expect(region.getByText(/此节点已正式作答，历史保留/)).toBeVisible()
  await region.getByText("保留的 JD 路线与原轮记录", { exact: true }).click()
  await expect(region.getByRole("link", { name: /查看作答、反馈与记录/ })).toBeVisible()
  await training.screenshot({ path: "test-results/jd-simulation-320.png" })
  expect(errors).toEqual([])
})

test("无岗位要求只补充、原文失响应重放不重复调用", async ({ page }) => {
  test.skip(!process.env.JD_BROWSER_TOKEN, "由 jd_browser.py 提供真实受控服务")
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.JD_BROWSER_TOKEN); await page.reload()
  const region = page.getByRole("region", { name: "JD 定向路线", exact: true })
  await region.getByRole("button", { name: "输入 JD 或恢复路线" }).click()
  await region.getByLabel("招聘原文", { exact: true }).fill("欢迎加入我们")
  await region.getByLabel("允许发送本次 JD").check()
  let identity = "", lost = false
  await page.route("**/api/v1/jds/analyze", async route => {
    const body = route.request().postDataJSON(); if (!identity) identity = body.request_id; else expect(body.request_id).toBe(identity)
    const response = await route.fetch()
    if (!lost) { lost = true; await route.abort("failed") } else await route.fulfill({ response })
  })
  await region.getByRole("button", { name: "分析 JD（先展示要求，不开题）" }).click()
  await expect(region.getByRole("alert")).toBeVisible()
  await expect(region.getByLabel("招聘原文", { exact: true })).toHaveValue("欢迎加入我们")
  await region.getByRole("button", { name: "分析 JD（先展示要求，不开题）" }).click()
  await expect(region.getByText("请补充具体岗位要求", { exact: true })).toBeVisible({ timeout: 15000 })
  await expect(region.getByRole("button", { name: /选择岗位：/ })).toHaveCount(0)
  await expect(region.getByRole("button", { name: "开始此 JD 教学模拟" })).toHaveCount(0)
})
