import { test, expect } from "@playwright/test"

test("固定公开源码模块路线、确认、键盘作答与原轮恢复", async ({ page }) => {
  test.skip(!process.env.PROJECT_TRAINING_TOKEN, "由 project_training_browser.py 提供隔离真实服务")
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message))
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.PROJECT_TRAINING_TOKEN)
  await page.goto(`/?project_run=${process.env.PROJECT_TRAINING_RUN_ID}`)
  const route = page.getByRole("region", { name: "项目模块学习路线", exact: true })
  await expect(route).toBeVisible()
  await route.getByRole("checkbox", { name: "允许发送项目模块片段" }).check()
  let lost = false
  await page.route("**/api/v1/project-training/analyze", async request => {
    if (lost) { await request.continue(); return }
    lost = true
    const response = await request.fetch()
    expect(response.status()).toBe(202)
    await request.abort("failed")
  })
  await route.getByRole("button", { name: "分析模块学习路线（不开题）" }).click()
  await expect(route.getByRole("alert")).toContainText("操作未确认成功")
  await route.getByRole("button", { name: "重新读取项目路线" }).click()
  await expect(route.getByLabel("模块训练重点")).toBeVisible({ timeout: 15000 })
  await expect(route.getByRole("button", { name: "开始模块教学练习" })).toBeDisabled()
  await route.getByLabel("模块训练重点").fill("重点核对 age 等于60与61的边界，不声称执行过代码")
  await expect(route.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeDisabled()
  await route.getByRole("button", { name: "保存模块目标为新版本" }).click()
  await expect(route.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeEnabled()
  await route.getByRole("button", { name: "确认模块路线（不生成题目）" }).focus(); await page.keyboard.press("Enter")
  await expect(route.getByRole("button", { name: "开始模块教学练习" })).toBeEnabled()
  await route.getByText("本次范围与缺项", { exact: true }).click()
  await expect(route).toContainText("未执行目标代码")
  await route.screenshot({ path: "test-results/project-training-320.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "200%")
  await route.getByRole("button", { name: "开始模块教学练习" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/project-training-200.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "")
  await route.getByRole("button", { name: "开始模块教学练习" }).click()
  await expect(page).toHaveURL(/training_run=/)
  const training = page.getByRole("region", { name: "随机第一关", exact: true })
  await expect(training.getByRole("complementary", { name: "项目教学来源" })).toContainText("教学假设")
  await expect(training.getByText("尚无已保存草稿", { exact: true })).toBeVisible({ timeout: 15000 })
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const radio = training.getByRole("radio").first()
  await expect(radio).toBeEnabled(); await radio.focus(); await page.keyboard.press("Space"); await expect(radio).toBeChecked()
  await training.getByLabel("这一判断的理由", { exact: true }).fill("源码严格大于而非大于等于，60等于max_age不触发过期，61应断言异常。")
  await expect(training.getByText("草稿已保存", { exact: true })).toBeVisible()
  await training.getByRole("checkbox").filter({ visible: true }).last().check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  await expect(training.getByText("通过", { exact: true })).toBeVisible({ timeout: 15000 })
  await page.reload()
  await expect(route.getByLabel("模块训练重点")).toHaveValue("重点核对 age 等于60与61的边界，不声称执行过代码")
  await expect(route.getByText("此节点已有正式作答，历史保留", { exact: true })).toBeVisible()
  await training.screenshot({ path: "test-results/project-feedback-320.png" })
  await training.getByText("通过", { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/project-feedback-viewport-320.png" })
  await route.getByRole("checkbox", { name: "允许发送项目模块片段" }).check()
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  let arrived!: () => void
  const accepted = new Promise<void>(resolve => { arrived = resolve })
  let started = ""
  await page.route("**/api/v1/topics/*/start", async request => {
    const response = await request.fetch()
    expect(response.status()).toBe(202)
    started = (await response.json()).id
    arrived()
    await gate
    await request.fulfill({ response })
  })
  const response = page.waitForResponse(r => r.url().includes("/topics/") && r.url().endsWith("/start"))
  await route.getByRole("button", { name: "开始模块教学练习" }).click()
  await accepted
  await page.getByLabel("查看已有项目任务").selectOption(process.env.PROJECT_TRAINING_OTHER_ID!)
  release()
  await (await response).finished()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await expect(page.getByLabel("查看已有项目任务")).toHaveValue(process.env.PROJECT_TRAINING_OTHER_ID!)
  expect(new URL(page.url()).searchParams.get("training_run")).not.toBe(started)
  const authorization = { Authorization: `Bearer ${process.env.PROJECT_TRAINING_TOKEN}` }
  const retained = await page.request.get(`/api/v1/training/tasks/${started}`, { headers: authorization })
  expect(retained.status()).toBe(200)
  await page.getByLabel("查看已有项目任务").selectOption(process.env.PROJECT_TRAINING_RUN_ID!)
  await route.getByLabel("模块训练重点").fill("保留A本机未保存输入")
  await page.getByLabel("查看已有项目任务").selectOption(process.env.PROJECT_TRAINING_OTHER_ID!)
  await page.getByLabel("查看已有项目任务").selectOption(process.env.PROJECT_TRAINING_RUN_ID!)
  await expect(route.getByLabel("模块训练重点")).toHaveValue("保留A本机未保存输入")
  expect(errors).toEqual([])
})

test("项目真实前置拒绝后保原项目路线返回身份", async ({ page }) => {
  test.skip(!process.env.PROJECT_TRAINING_TOKEN, "由 project_training_browser.py 提供隔离真实服务")
  const headers = { Authorization: `Bearer ${process.env.PROJECT_TRAINING_TOKEN}` }
  const routes = await (await page.request.get("/api/v1/project-training", { headers })).json()
  const item = routes.find((r: { project_run_id: string }) => r.project_run_id === process.env.PROJECT_TRAINING_RUN_ID)
  const version = item.current.route
  const node = version.nodes[0]
  const edit = await page.request.post(`/api/v1/topics/${item.topic.id}/edit`, { headers, data: { expected_version: version.id, operation: "edit", node_id: node.id, goal: { target: { ...node.target, difficulty: "综合" }, text: node.text, focus: node.focus } } })
  expect(edit.status()).toBe(200)
  const changed = (await edit.json()).current
  expect((await page.request.post(`/api/v1/topics/${item.topic.id}/confirm`, { headers, data: { expected_version: changed.id } })).status()).toBe(200)
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.PROJECT_TRAINING_TOKEN)
  await page.goto(`/?project_run=${process.env.PROJECT_TRAINING_RUN_ID}&project_route=${item.topic.id}`)
  const route = page.getByRole("region", { name: "项目模块学习路线", exact: true })
  await route.getByRole("checkbox", { name: "允许发送项目模块片段" }).check()
  await route.getByRole("button", { name: "开始模块教学练习" }).click()
  const missing = route.getByRole("region", { name: "项目实际前置缺项" })
  await expect(missing).toBeVisible()
  await missing.getByRole("link").first().click()
  const url = new URL(page.url())
  expect(url.searchParams.get("project_run")).toBe(process.env.PROJECT_TRAINING_RUN_ID)
  expect(url.searchParams.get("project_route")).toBe(item.topic.id)
  await expect(page.getByLabel("查看已有项目任务")).toHaveValue(process.env.PROJECT_TRAINING_RUN_ID!)
  await expect(route.getByLabel("模块训练目标")).toHaveValue(node.text)
})
