import { test, expect } from "@playwright/test"

test("固定公开源码模块路线、确认、键盘作答与原轮恢复", async ({ page }) => {
  test.skip(!process.env.PROJECT_TRAINING_TOKEN, "由 project_training_browser.py 提供隔离真实服务")
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message))
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.PROJECT_TRAINING_TOKEN)
  await page.goto(`/?project_run=${process.env.PROJECT_TRAINING_RUN_ID}`)
  const route = page.getByRole("region", { name: "项目模块学习路线", exact: true })
  await expect(route).toBeVisible()
  await route.getByRole("checkbox", { name: "允许发送项目模块片段" }).check()
  await route.getByRole("button", { name: "分析模块学习路线（不开题）" }).click()
  await expect(route.getByLabel("模块训练重点")).toBeVisible({ timeout: 15000 })
  await expect(route.getByRole("button", { name: "开始模块教学练习" })).toBeDisabled()
  await route.getByLabel("模块训练重点").fill("重点核对 age 等于60与61的边界，不声称执行过代码")
  await expect(route.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeDisabled()
  await route.getByRole("button", { name: "保存模块目标为新版本" }).click()
  await expect(route.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeEnabled()
  await route.getByRole("button", { name: "确认模块路线（不生成题目）" }).focus(); await page.keyboard.press("Enter")
  await expect(route.getByRole("button", { name: "开始模块教学练习" })).toBeEnabled()
  await route.getByText("本次范围与缺项", { exact: true }).click()
  await expect(route).toContainText("未执行目标代码")
  await route.screenshot({ path: "test-results/project-training-320.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "200%")
  await route.getByRole("button", { name: "开始模块教学练习" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: "test-results/project-training-200.png" })
  await page.evaluate(() => document.documentElement.style.fontSize = "")
  await route.getByRole("button", { name: "开始模块教学练习" }).click()
  await expect(page).toHaveURL(/training_run=/)
  const training = page.getByRole("region", { name: "随机第一关", exact: true })
  await expect(training.getByRole("complementary", { name: "项目教学来源" })).toContainText("教学假设")
  await expect(training.getByText("尚无已保存草稿", { exact: true })).toBeVisible({ timeout: 15000 })
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const radio = training.getByRole("radio").first()
  await expect(radio).toBeEnabled(); await radio.focus(); await page.keyboard.press("Space"); await expect(radio).toBeChecked()
  await training.getByLabel("这一判断的理由", { exact: true }).fill("源码严格大于而非大于等于，60等于max_age不触发过期，61应断言异常。")
  await expect(training.getByText("草稿已保存", { exact: true })).toBeVisible()
  await training.getByRole("checkbox").filter({ visible: true }).last().check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  await expect(training.getByText("通过", { exact: true })).toBeVisible({ timeout: 15000 })
  await page.reload()
  await expect(route.getByLabel("模块训练重点")).toHaveValue("重点核对 age 等于60与61的边界，不声称执行过代码")
  await expect(route.getByText("此节点已有正式作答，历史保留", { exact: true })).toBeVisible()
  await training.screenshot({ path: "test-results/project-feedback-320.png" })
  await training.getByText("通过", { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/project-feedback-viewport-320.png" })
  expect(errors).toEqual([])
})
