import { test, expect } from "@playwright/test"

test("跨路线保留相同节点身份但本机修改严格隔离", async ({ page }) => {
  test.skip(!process.env.PROJECT_UPDATES_TOKEN, "由本票受控 worker 和真实 API 准备")
  await page.goto("/")
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.PROJECT_UPDATES_TOKEN)
  await page.goto(`/?project_run=${process.env.PROJECT_UPDATES_SOURCE}&project_route=${process.env.PROJECT_UPDATES_A}`)
  const region = page.getByRole("region", { name: "项目模块学习路线", exact: true })
  const picker = region.getByLabel("已有路线")
  const focus = region.getByLabel("模块训练重点", { exact: true })
  await expect(picker).toHaveValue(process.env.PROJECT_UPDATES_A!)
  const saved = await focus.inputValue()
  await focus.fill("A 专属未保存重点")
  await picker.selectOption(process.env.PROJECT_UPDATES_B!)
  await expect(focus).toHaveValue(saved)
  await focus.fill("B 专属未保存重点")
  await expect(region.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeDisabled()
  await picker.selectOption(process.env.PROJECT_UPDATES_A!)
  await expect(focus).toHaveValue("A 专属未保存重点")
  await picker.selectOption(process.env.PROJECT_UPDATES_B!)
  await expect(focus).toHaveValue("B 专属未保存重点")
  await region.getByRole("button", { name: "保存模块目标为新版本" }).click()
  await expect(region.getByRole("button", { name: "确认模块路线（不生成题目）" })).toBeEnabled()
  await picker.selectOption(process.env.PROJECT_UPDATES_A!)
  await expect(focus).toHaveValue("A 专属未保存重点")
  await region.getByRole("button", { name: "重新读取项目路线" }).click()
  await expect(focus).toHaveValue("A 专属未保存重点")
})
