import { expect, test } from "@playwright/test"

test("公开项目真实读取、同版本复用和320px键盘地图", async ({ page }) => {
  test.skip(!process.env.PROJECT_BROWSER_TOKEN, "由backend/tests/project_browser.py启动受控GitHub/模型TLS与独立worker")
  await page.setViewportSize({ width: 320, height: 760 })
  await page.goto("/")
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.PROJECT_BROWSER_TOKEN)
  await page.reload()
  const project = page.getByRole("region", { name: "公开 GitHub 项目地图", exact: true })
  await expect(project.getByText(/本次资料接收方/)).toBeVisible()
  await project.getByRole("textbox", { name: "公开 GitHub HTTPS 链接" }).fill("https://github.com/test/project.git")
  await project.getByRole("checkbox", { name: /^允许将当前公开源码必要片段及上下文/ }).check()
  await project.getByRole("button", { name: "按链接读取或主动更新版本" }).focus()
  await page.keyboard.press("Enter")
  await expect(project.getByRole("button", { name: "停止分析", exact: true })).toBeVisible()
  await project.scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/project-running-mobile.png" })
  await page.reload()
  await expect(project.getByRole("status").filter({ hasText: /初版地图已保留/ })).toBeVisible({ timeout: 15000 })
  await expect(project.getByRole("heading", { name: "已确认源码事实" })).toBeVisible()
  await project.getByText("目录与未读范围", { exact: true }).click()
  await expect(project.getByText("external · 符号链接或子模块，不读取目标", { exact: true })).toBeVisible()
  await project.getByText("固定版本来源片段", { exact: true }).click()
  await project.locator("summary").filter({ hasText: "main.py · 行 1–8" }).click()
  expect(await page.evaluate(() => (window as unknown as { injected?: boolean }).injected)).toBeUndefined()
  await expect(project.getByRole("link", { name: "核对 GitHub 固定行范围" })).toHaveAttribute("href", /blob\/a{40}\/main.py#L1-L8/)
  await project.getByRole("heading", { name: "已确认源码事实" }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/project-result-mobile.png" })
  await project.getByRole("textbox", { name: "公开 GitHub HTTPS 链接" }).fill("https://github.com/test/project.git")
  await project.getByRole("checkbox", { name: /^允许将当前公开源码必要片段及上下文/ }).check()
  await project.getByRole("button", { name: "按链接读取或主动更新版本" }).click()
  await expect(project.getByRole("status").filter({ hasText: /固定版本未变化，展示已有分析/ })).toBeVisible({ timeout: 15000 })
  await project.getByRole("button", { name: "主动重分析当前固定版本（可能计费）" }).click()
  await expect(project.getByRole("status").filter({ hasText: /初版地图已保留/ })).toBeVisible({ timeout: 15000 })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await project.getByRole("button", { name: "主动重分析当前固定版本（可能计费）" }).scrollIntoViewIfNeeded()
  await expect(project.getByRole("button", { name: "主动重分析当前固定版本（可能计费）" })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: "test-results/project-200-mobile.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "" })
  await page.setViewportSize({ width: 1200, height: 900 })
  const facts = project.getByRole("region", { name: "已确认源码事实", exact: true })
  const unverified = project.getByRole("region", { name: "未核实候选与缺失材料", exact: true })
  const left = await facts.boundingBox(), right = await unverified.boundingBox()
  expect(left!.x).toBeLessThan(right!.x)
})
