import { expect, test, type Page } from "@playwright/test"

test("随机偏好真实跨设备CAS、失响应恢复、固定空池及新轮冻结", async ({ page, browser, request }) => {
  test.skip(!process.env.RANDOM_BROWSER_TOKEN, "由 random_browser.py 提供真实正式作答")
  const token = process.env.RANDOM_BROWSER_TOKEN!
  const headers = { Authorization: `Bearer ${token}` }
  const original = process.env.RANDOM_ORIGINAL_RUN!
  const originalState = await (await request.get(`/api/v1/training/tasks/${original}/submissions`, { headers })).json()
  const errors: string[] = []
  page.on("pageerror", e => errors.push(e.message))
  async function enter(p: Page) {
    await p.goto("/"); await p.evaluate(t => sessionStorage.setItem("token", t), token); await p.reload()
    await expect(p.getByText("账号偏好已确认，之后新任务沿用；当前题目与草稿不变。", { exact: true })).toBeVisible()
  }
  await page.setViewportSize({ width: 320, height: 760 })
  await enter(page)
  const device = await browser.newContext({ baseURL: test.info().project.use.baseURL, viewport: { width: 320, height: 760 } })
  const other = await device.newPage()
  await enter(other)
  const select = page.getByLabel("随机练习难度", { exact: true })
  const otherSelect = other.getByLabel("随机练习难度", { exact: true })
  await select.selectOption("基础")
  await page.getByRole("button", { name: "保存难度偏好", exact: true }).click()
  await expect(page.getByText("账号偏好已确认，之后新任务沿用；当前题目与草稿不变。", { exact: true })).toBeVisible()
  await otherSelect.selectOption("进阶")
  await other.getByRole("button", { name: "保存难度偏好", exact: true }).click()
  await expect(other.getByText("另一设备已修改偏好，请重读后重新选择；当前题和输入不变。", { exact: true })).toBeVisible()
  await expect(otherSelect).toHaveValue("进阶")
  await other.getByRole("button", { name: "重新读取难度偏好", exact: true }).click()
  await expect(otherSelect).toHaveValue("基础")
  await otherSelect.selectOption("综合")
  // Server saved; a lost response cannot falsely label the local mode saved.
  await other.route("**/training/random-preference", async route => {
    if (route.request().method() !== "PUT") return route.continue()
    await route.fetch(); await route.abort()
  })
  await other.getByRole("button", { name: "保存难度偏好", exact: true }).click()
  await expect(other.getByText("偏好未确认保存，保留当前选择；请重读确认或重试。", { exact: true })).toBeVisible()
  await expect(otherSelect).toHaveValue("综合")
  await other.unroute("**/training/random-preference")
  await other.getByRole("button", { name: "重新读取难度偏好", exact: true }).click()
  await other.reload()
  await expect(otherSelect).toHaveValue("综合")
  const training = other.getByRole("region", { name: "随机第一关" })
  await training.getByRole("checkbox").first().check()
  await training.getByRole("button", { name: "换个方向，主动开始新一关", exact: true }).click()
  await expect(training.getByRole("alert")).toContainText("当前方向和难度没有可用目标")
  await expect(training.getByRole("link", { name: /核对前置与补基础/ }).first()).toBeVisible()
  await expect(otherSelect).toHaveValue("综合")
  await otherSelect.selectOption("基础")
  await other.getByRole("button", { name: "保存难度偏好", exact: true }).click()
  await expect(training.getByRole("button", { name: "换个方向，主动开始新一关", exact: true })).toBeEnabled()
  await training.getByRole("button", { name: "换个方向，主动开始新一关", exact: true }).click()
  await expect(other).toHaveURL(/training_run=/)
  const newRun = new URL(other.url()).searchParams.get("training_run")!
  expect(newRun).toBeTruthy()
  await expect(training.getByText("已核对案例已保留；教学质量未验收", { exact: true })).toBeVisible()
  expect(newRun).not.toBe(original)
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const reason = other.getByLabel("这一判断的理由", { exact: true }).first()
  await reason.fill("固定难度的新题草稿不随偏好变化")
  await expect(other.getByText("草稿已保存", { exact: true })).toBeVisible()
  await otherSelect.selectOption("recommended")
  await other.getByRole("button", { name: "保存难度偏好", exact: true }).click()
  await other.reload()
  await expect(reason).toHaveValue("固定难度的新题草稿不随偏好变化")
  const run = await (await request.get(`/api/v1/training/tasks/${newRun}`, { headers })).json()
  expect(run.random_mode).toBe("基础")
  expect(run.target.difficulty).toBe("基础")
  expect(run.current_mode).toBe("practice")
  expect(await (await request.get(`/api/v1/training/tasks/${original}/submissions`, { headers })).json()).toEqual(originalState)
  await page.getByRole("button", { name: "重新读取难度偏好", exact: true }).click()
  await select.scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/random-320.png" })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  await select.scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/random-200.png" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await device.close()
})

test("偏好读取与保存迟到响应不覆盖之后编辑", async ({ page }) => {
  test.skip(!process.env.RANDOM_BROWSER_TOKEN, "由 random_browser.py 提供真实账号")
  await page.goto("/")
  await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.RANDOM_BROWSER_TOKEN)
  await page.reload()
  await expect(page.getByText("账号偏好已确认，之后新任务沿用；当前题目与草稿不变。", { exact: true })).toBeVisible()
  const select = page.getByLabel("随机练习难度", { exact: true })
  for (const method of ["GET", "PUT"]) {
    let release!: () => void, received!: () => void
    const pending = new Promise<void>(resolve => { release = resolve })
    const started = new Promise<void>(resolve => { received = resolve })
    await page.route("**/training/random-preference", async route => {
      if (route.request().method() !== method) return route.continue()
      const response = await route.fetch()
      received(); await pending; await route.fulfill({ response })
    })
    if (method === "GET") await page.getByRole("button", { name: "重新读取难度偏好", exact: true }).click()
    else await page.getByRole("button", { name: "保存难度偏好", exact: true }).click()
    await started
    const next = method === "GET" ? "综合" : "基础"
    await select.selectOption(next)
    release()
    await expect(page.getByRole("button", { name: "重新读取难度偏好", exact: true })).toBeEnabled()
    await expect(select).toHaveValue(next)
    await expect(page.getByText("偏好尚未确认；请先保存或重读，当前题目与草稿不变。", { exact: true })).toBeVisible()
    await page.unroute("**/training/random-preference")
  }
})
