import { expect, test } from "@playwright/test"

test("本批真实普通作答与方向帮助后的独立轮", async ({ page }) => {
  test.skip(!process.env.SERVICE_DATA_TOKEN, "仅由本批专用 harness 启用")
  const origin = process.env.SERVICE_DATA_ORIGIN!
  const draft = JSON.parse(process.env.SERVICE_DATA_DRAFT!)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto(`/?training_run=${origin}`)
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.SERVICE_DATA_TOKEN)
  await page.reload()
  const training = page.getByRole("region", { name: "随机第一关" })
  const saved = training.getByLabel("草稿保存状态").getByRole("status")
  await expect(saved).toHaveText("尚无已保存草稿")
  await expect(training.getByText(draft.candidate.title, { exact: true })).toBeVisible()
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const reason = training.getByLabel("这一判断的理由", { exact: true }).first()
  const wrong = training.getByRole("radio").nth(1)
  await expect(wrong).toBeEnabled()
  await wrong.focus()
  await page.keyboard.press("Space")
  await expect(wrong).toBeChecked()
  await reason.fill(draft.answers[1].answer.reason)
  await training.getByRole("checkbox", { name: /允许将当前公开题面与作答/ }).check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  const feedback = page.getByRole("region", { name: "本次反馈" })
  await expect(feedback.getByText("有据未通过", { exact: true })).toBeVisible({ timeout: 15000 })
  await expect(training.getByText(/本轮已完成，自动获得 10 点/)).toBeVisible()
  await expect(saved).toHaveText("草稿已保存")
  await feedback.screenshot({ path: `test-results/${draft.id}-ordinary.png` })
  await training.getByRole("checkbox", { name: /允许发送必要的新旧情境/ }).check()
  const creating = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/independent"))
  await training.getByRole("button", { name: "检验自己：主动新建陌生案例" }).click()
  const created = await (await creating).json()
  expect(created.id).not.toBe(origin)
  expect(created.case).toBeNull()
  await expect(training.getByRole("status").filter({ hasText: "主动检验案例已就绪" })).toBeVisible({ timeout: 15000 })
  await expect(saved).toHaveText("尚无已保存草稿")
  await training.getByRole("button", { name: "概念", exact: true }).click()
  const coach = page.getByRole("region", { name: "概念教练" })
  await coach.getByRole("checkbox", { name: /允许/ }).check()
  await coach.getByRole("button", { name: "证据提示", exact: true }).click()
  const show = coach.getByRole("button", { name: "查看证据提示" })
  await expect(show).toBeVisible({ timeout: 15000 })
  await expect(show).toBeDisabled()
  const consent = coach.getByRole("checkbox", { name: /继续后本题转为练习/ })
  await consent.check()
  const rendered = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/receipt"))
  await show.click()
  expect((await rendered).status()).toBe(200)
  await training.getByRole("button", { name: "判断", exact: true }).click()
  const correct = training.getByRole("radio").first()
  await expect(correct).toBeEnabled()
  await correct.check()
  await reason.fill(draft.positive_variant.rubric[0].reasoning)
  await training.getByRole("checkbox", { name: /允许将当前公开题面与作答/ }).check()
  await training.getByRole("button", { name: "正式交卷", exact: true }).click()
  await expect(feedback.getByText(/按练习记录，已有修为保留/)).toBeVisible({ timeout: 15000 })
  await expect(saved).toHaveText("草稿已保存")
  await feedback.screenshot({ path: `test-results/${draft.id}-directional.png` })
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await feedback.scrollIntoViewIfNeeded()
  await page.screenshot({ path: `test-results/${draft.id}-200.png` })
  await page.goto(`/?training_run=${origin}`)
  await expect(saved).toHaveText("草稿已保存")
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await training.getByText(/已保存原答与补充记录/).click()
  await expect(training.locator("details").filter({ has: page.locator("summary").filter({ hasText: "已保存原答与补充记录" }) }).getByText(`理由：${draft.answers[1].answer.reason}`, { exact: false })).toBeVisible()
  expect(errors).toEqual([])
})
