import { expect, test } from "@playwright/test"

test("自由主题真实分析、编辑确认、开题作答反馈与旧路线恢复", async ({ page }) => {
  test.skip(!process.env.TOPIC_BROWSER_TOKEN, "由topic_browser.py提供真实受控服务")
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message))
  await page.setViewportSize({ width:320, height:780 })
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.TOPIC_BROWSER_TOKEN); await page.reload()
  const region = page.getByRole("region", { name:"自由主题入口" })
  await region.getByRole("button", { name:"输入自由主题或恢复路线" }).click()
  await expect(region.getByRole("link", { name:/还没想好/ })).toBeVisible()
  await region.getByLabel("想练什么", { exact:true }).fill("请求超时后怎样判断能否重试？")
  await region.getByRole("checkbox").check()
  await region.getByRole("button", { name:"分析主题，先看目标卡" }).click()
  await expect(region.getByLabel("目标", { exact:true })).toBeVisible({ timeout:15000 })
  await expect(region.getByRole("button", { name:"开始这个目标（生成一题）" })).toBeDisabled()
  await region.getByLabel("重点", { exact:true }).fill("比较确认丢失与执行证据，不把超时等同未执行")
  await region.getByRole("button", { name:"保存为新候选版本" }).click()
  await expect(region.getByRole("button", { name:"保存为新候选版本" })).toBeDisabled()
  await expect(region.getByRole("button", { name:"确认当前路线版本（不生成题目）" })).toBeEnabled()
  await region.getByRole("button", { name:"确认当前路线版本（不生成题目）" }).focus(); await page.keyboard.press("Enter")
  await expect(region.getByRole("button", { name:"开始这个目标（生成一题）" })).toBeEnabled()
  await region.screenshot({ path:"test-results/topic-320.png" })
  await page.evaluate(() => document.documentElement.style.fontSize="200%")
  await region.getByRole("button", { name:"开始这个目标（生成一题）" }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path:"test-results/topic-200.png" })
  await page.evaluate(() => document.documentElement.style.fontSize="")
  await region.getByRole("button", { name:"开始这个目标（生成一题）" }).click()
  await expect(page).toHaveURL(/training_run=/)
  const training = page.getByRole("region", { name:"随机第一关" })
  await expect(training.getByText("已核对案例已保留；教学质量未验收", { exact:true })).toBeVisible({ timeout:15000 })
  await expect(training.getByText("尚无已保存草稿", { exact:true })).toBeVisible()
  await training.getByRole("button", { name:"判断", exact:true }).click()
  await training.getByRole("radio").first().check()
  await training.getByLabel("这一判断的理由", { exact:true }).fill("确认可能丢失，需要补查实际执行记录后决定")
  await expect(training.getByText("草稿已保存", { exact:true })).toBeVisible()
  await training.getByRole("checkbox").filter({ visible:true }).last().check()
  const submit = training.getByRole("button", { name:"正式交卷", exact:true })
  await submit.click()
  await expect(training.getByText("通过", { exact:true })).toBeVisible({ timeout:15000 })
  await page.reload()
  await expect(region.getByLabel("重点", { exact:true })).toHaveValue("比较确认丢失与执行证据，不把超时等同未执行")
  await region.getByText("历史路线与已开始的题目", { exact:true }).click()
  await expect(region.getByRole("link", { name:/查看原轮作答/ })).toBeVisible()
  await expect(region.getByText("此节点已有完整正式作答，原轮记录保留", { exact:true })).toBeVisible()
  expect(errors).toEqual([])
})

test("宽泛逐段展开、六节点局部修改和跨设备冲突保留输入", async ({ page, browser }) => {
  test.skip(!process.env.TOPIC_BROWSER_TOKEN, "由topic_browser.py提供真实受控服务")
  const token=process.env.TOPIC_BROWSER_TOKEN!
  async function enter(p: typeof page) { await p.goto("/"); await p.evaluate(t=>sessionStorage.setItem("token",t),token); await p.reload(); await p.getByRole("button",{name:"输入自由主题或恢复路线"}).click() }
  await enter(page)
  const region=page.getByRole("region",{name:"自由主题入口"})
  await region.getByLabel("想练什么",{exact:true}).fill("网络路线")
  await region.getByRole("checkbox").check()
  await region.getByRole("button",{name:"分析主题，先看目标卡"}).click()
  await expect(region.getByLabel("目标",{exact:true})).toHaveCount(3,{timeout:15000})
  await region.getByLabel("想练什么",{exact:true}).fill("网络路线下一段")
  await region.getByRole("button",{name:"按当前输入展开下一段（不生成题目）"}).click()
  await expect(region.getByLabel("目标",{exact:true})).toHaveCount(6,{timeout:15000})
  const topic=new URL(page.url()).searchParams.get("topic")!
  const device=await browser.newContext({baseURL:test.info().project.use.baseURL})
  const other=await device.newPage(); await other.goto("/"); await other.evaluate(t=>sessionStorage.setItem("token",t),token); await other.goto(`/?topic=${topic}`)
  const otherRegion=other.getByRole("region",{name:"自由主题入口"})
  await expect(otherRegion.getByLabel("目标",{exact:true})).toHaveCount(6)
  await region.getByLabel("重点",{exact:true}).first().fill("第一项尚未保存的输入必须保留")
  await region.getByLabel("重点",{exact:true}).nth(4).fill("第五个节点更新保留其余五项")
  await region.getByRole("button",{name:"保存为新候选版本"}).nth(4).click()
  await expect(region.getByRole("button",{name:"确认当前路线版本（不生成题目）"})).toBeEnabled()
  await expect(region.getByRole("button",{name:"保存为新候选版本"}).nth(4)).toBeDisabled()
  await expect(region.getByLabel("重点",{exact:true}).first()).toHaveValue("第一项尚未保存的输入必须保留")
  await otherRegion.getByLabel("重点",{exact:true}).nth(4).fill("另一设备尚未保存的本地重点")
  await otherRegion.getByRole("button",{name:"保存为新候选版本"}).nth(4).click()
  await expect(otherRegion.getByRole("alert")).toContainText("路线已变化")
  await expect(otherRegion.getByLabel("重点",{exact:true}).nth(4)).toHaveValue("另一设备尚未保存的本地重点")
  let release!: () => void
  let arrived!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  const received = new Promise<void>(resolve => { arrived = resolve })
  await other.route("**/api/v1/topics", async route => { const response = await route.fetch(); arrived(); await held; await route.fulfill({ response }) })
  await otherRegion.getByRole("button", { name:"重新读取路线与模型目的地" }).click()
  await received
  await otherRegion.getByLabel("重点", { exact:true }).first().fill("读回期间输入也必须保留")
  release()
  await expect(otherRegion.getByRole("region", { name:"保留的本机目标修改" })).toContainText("另一设备尚未保存的本地重点")
  await expect(otherRegion.getByLabel("重点", { exact:true }).first()).toHaveValue("读回期间输入也必须保留")
  await expect(otherRegion.getByLabel("重点", { exact:true }).nth(4)).toHaveValue("第五个节点更新保留其余五项")
  await other.unroute("**/api/v1/topics")
  await other.setViewportSize({ width:320, height:780 })
  await other.evaluate(() => document.documentElement.style.fontSize="200%")
  const retained = otherRegion.getByRole("region", { name:"保留的本机目标修改" })
  await retained.scrollIntoViewIfNeeded()
  expect(await other.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await retained.screenshot({ path:"test-results/topic-local-conflict-200.png" })
  await expect(region.getByLabel("目标",{exact:true})).toHaveCount(6)
  await page.reload()
  await expect(region.getByLabel("重点",{exact:true}).nth(4)).toHaveValue("第五个节点更新保留其余五项")
  await expect(region.getByRole("button",{name:"开始这个目标（生成一题）"}).first()).toBeDisabled()
  await device.close()
})


test("已确认进阶主题显示真实缺项并保留原主题补练出口", async ({ page }) => {
  test.skip(!process.env.TOPIC_BROWSER_TOKEN, "由topic_browser.py提供真实受控服务")
  await page.goto("/"); await page.evaluate(t => sessionStorage.setItem("token", t!), process.env.TOPIC_BROWSER_TOKEN); await page.reload()
  const region=page.getByRole("region",{name:"自由主题入口"})
  await region.getByRole("button",{name:"输入自由主题或恢复路线"}).click()
  await region.getByLabel("想练什么",{exact:true}).fill("请求超时后怎样判断能否重试？")
  await region.getByRole("checkbox").check()
  await region.getByRole("button",{name:"分析主题，先看目标卡"}).click()
  await expect(region.getByLabel("目标难度")).toBeVisible({timeout:15000})
  await region.getByLabel("目标难度").selectOption("进阶")
  await region.getByRole("button",{name:"保存为新候选版本"}).click()
  await expect(region.getByRole("button",{name:"确认当前路线版本（不生成题目）"})).toBeEnabled()
  await region.getByRole("button",{name:"确认当前路线版本（不生成题目）"}).click()
  await expect(region.getByRole("button",{name:"开始这个目标（生成一题）"})).toBeEnabled()
  const topic=new URL(page.url()).searchParams.get("topic")!
  await region.getByRole("button",{name:"开始这个目标（生成一题）"}).click()
  const missing=region.getByRole("region",{name:"主题目标缺失前置"})
  await expect(missing).toBeVisible()
  await expect(region.getByRole("alert")).not.toContainText("操作未确认成功")
  await expect(region.getByLabel("目标难度")).toHaveValue("进阶")
  await page.setViewportSize({width:320,height:780})
  await page.evaluate(() => document.documentElement.style.fontSize="200%")
  await missing.scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await missing.screenshot({path:"test-results/topic-prerequisite-200.png"})
  await missing.getByRole("link").first().click()
  expect(new URL(page.url()).searchParams.get("topic")).toBe(topic)
  await expect(page.getByRole("region",{name:"目标解锁与补基础"})).toBeVisible()
  await expect(region.getByLabel("目标难度")).toHaveValue("进阶")
})
