import { expect, test } from "@playwright/test"

test("真实任务恢复、隐藏答案隔离和320px键盘工作台", async ({ page }) => {
  test.skip(!process.env.TRAINING_BROWSER_TOKEN, "由backend/tests/training_browser.py启动受控TLS供应商和独立worker")
  await page.setViewportSize({ width: 320, height: 760 })
  await page.goto("/")
  await page.evaluate(token => sessionStorage.setItem("token", token!), process.env.TRAINING_BROWSER_TOKEN)
  await page.reload()
  const training = page.getByRole("region", { name: "随机第一关" })
  await expect(training.getByText(/本次资料接收方/)).toBeVisible()
  await training.getByRole("checkbox").check()
  await training.getByRole("button", { name: "帮我选一关" }).focus()
  await page.keyboard.press("Enter")
  await expect(training.getByRole("button", { name: "停止本次生成" })).toBeVisible()
  await page.reload()
  await expect(training.getByText("比较请求证据", { exact: true })).toBeVisible({ timeout: 15000 })
  await expect(page.locator("script").filter({ hasText: "window.injection=true" })).toHaveCount(0)
  expect(await page.evaluate(() => (window as unknown as { injection?: boolean }).injection)).toBeUndefined()
  await training.getByRole("button", { name: "判断", exact: true }).click()
  await training.getByRole("radio").first().focus()
  await page.keyboard.press("Space")
  await expect(training.getByRole("radio").first()).toBeChecked()
  await training.getByRole("textbox", { name: "这一判断的理由" }).fill("应先核对确认是否丢失。")
  await expect(training.getByText(/尚未保存或正式交卷/)).toBeVisible()
  expect(await page.content()).not.toContain("HIDDEN_REASON")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await training.getByRole("heading", { name: "比较请求证据" }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: "test-results/training-mobile.png" })
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(training.getByRole("region", { name: "案例材料" })).toBeVisible()
  await expect(training.getByRole("region", { name: "必答判断" })).toBeVisible()
  await page.evaluate(() => { document.documentElement.style.fontSize = "200%" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test("真实SDK读取null配置时不显示空接收方或启动入口", async ({ page, request }) => {
  test.skip(!process.env.TRAINING_UNCONFIGURED_TOKEN, "由training_browser.py提供真实未配置账号")
  const token = process.env.TRAINING_UNCONFIGURED_TOKEN!
  const response = await request.get("/api/v1/model-config", { headers: { Authorization: `Bearer ${token}` } })
  expect(await response.json()).toBeNull()
  await page.goto("/")
  await page.evaluate(value => sessionStorage.setItem("token", value), token)
  await page.reload()
  const training = page.getByRole("region", { name: "随机第一关" })
  await expect(training.getByText("请在账号与模型区域保存配置，再重新读取目的地。")).toBeVisible()
  await expect(training.getByText(/本次资料接收方/)).toHaveCount(0)
  await expect(training.getByRole("checkbox")).toHaveCount(0)
  await expect(training.getByRole("button", { name: "帮我选一关" })).toHaveCount(0)
})
