import { expect,test } from '@playwright/test'

test('真实前置缺项、直接检验两轮、解锁返回与保留原目标',async({page})=>{
  test.skip(!process.env.UNLOCK_BROWSER_TOKEN,'由受控真实worker提供')
  await page.addInitScript(token=>sessionStorage.setItem('token',token!),process.env.UNLOCK_BROWSER_TOKEN)
  await page.setViewportSize({width:320,height:850})
  await page.goto('/?capability=network.delivery&difficulty=进阶')
  const unit=page.getByRole('region',{name:'目标解锁与补基础'})
  await expect(unit.getByText('尚不能打开新学习单元，请选择下面实际缺失的证明。')).toBeVisible()
  await expect(unit.getByRole('button',{name:'练习当前目标（不授予证明）'})).toHaveCount(0)
  await unit.screenshot({path:'test-results/unlock-blocked-320.png'})
  for(let index=0;index<2;index++){
    await unit.getByRole('button',{name:'针对这项补练或检验'}).click()
    await expect(unit.getByRole('heading',{name:/当前目标：.*基础/})).toBeVisible()
    await unit.getByRole('checkbox').check()
    await unit.getByRole('button',{name:'直接检验当前能力（新陌生案例）'}).focus()
    await page.keyboard.press('Enter')
    const training=page.getByRole('region',{name:'随机第一关'})
    await expect(training.getByRole('status').filter({hasText:'主动检验案例已就绪'})).toBeVisible({timeout:15000})
    const saved=training.getByLabel('草稿保存状态').getByRole('status')
    await expect(saved).toHaveText('尚无已保存草稿')
    await training.getByRole('button',{name:'判断',exact:true}).click()
    await training.getByRole('radio').first().check()
    await training.getByLabel('这一判断的理由',{exact:true}).fill('依据当前材料判断下一步。')
    await training.getByRole('checkbox',{name:/允许将当前公开题面/}).check()
    await training.getByRole('button',{name:'正式交卷',exact:true}).click()
    const feedback=page.getByRole('region',{name:'本次反馈'})
    await expect(feedback.getByText(/符合独立通过条件的证据候选/)).toBeVisible({timeout:15000})
    await expect(saved).toHaveText('草稿已保存')
    await training.getByRole('link',{name:'返回原目标并核对解锁条件'}).click()
    await expect(unit.getByRole('heading',{name:/当前目标：.*进阶/})).toBeVisible()
    await expect(unit.getByText(index===0?'尚不能打开新学习单元，请选择下面实际缺失的证明。':'当前前置条件已满足，可明确打开学习单元。')).toBeVisible()
  }
  await unit.getByRole('button',{name:'打开这个学习单元'}).click()
  await expect(unit.getByText('这个学习单元已经开放；前置后来待巩固也保留入口。')).toBeVisible()
  await page.reload()
  await expect(unit.getByText('这个学习单元已经开放；前置后来待巩固也保留入口。')).toBeVisible()
  await page.evaluate(()=>{document.documentElement.style.fontSize='200%'})
  await unit.scrollIntoViewIfNeeded()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await unit.screenshot({path:'test-results/unlock-open-200.png'})
  await unit.getByRole('checkbox').check()
  await unit.getByRole('button',{name:'练习当前目标（不授予证明）'}).click()
  await expect(page.getByRole('region',{name:'随机第一关'}).getByRole('status').filter({hasText:'已核对案例已保留'})).toBeVisible({timeout:15000})
  await expect(page.getByText('本轮默认练习；普通练习通过不会自动成为独立证明。')).toBeVisible()
})
